### ISSUE TITLE
CairoMakie ignores vspan alpha

### ISSUE THREAD

**Issue by aplavin** [MakieOrg/Makie.jl#4626] opened 2024-11-25 22:58 UTC
Running `vspan(0..1, color=:red, alpha=0.1)` results in this with GLMakie (expected):
![Image](https://github.com/user-attachments/assets/a53bf3ba-b7bb-415c-9a65-8670960c2f72)
and this with CairoMakie (alpha is ignored):
![Image](https://github.com/user-attachments/assets/bb26334a-8ff1-4dba-9f8f-55c163d0e8d9)

   
- [x] what version of Makie are you running? (`]st -m Makie`) latest
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`) latest
- [x] What platform + GPU are you on? macbook m2

**Comment by lanceXwq** [comment] 2024-11-26 18:56
I have the same problem. `vspan(0..1, color=(:red, 0.1))` works while `vspan(0..1, color=:red, alpha=0.1)` does not. This also seems to happen to `scatterlines`.

**Comment by ffreyer** [comment] 2024-11-26 20:16
This is more or less a duplicate of #3735, because vspan/hspan rely on poly. Whatever comes out of #4360 will most likely revamp the color internals so it's not a priority right now and it may get fixed there.

**Closed** 2024-12-02 14:23 UTC
Labels: bug, CairoMakie
