### ISSUE TITLE
How to block until displayed?

### ISSUE THREAD

**Issue by jtrakk** [MakieOrg/Makie.jl#1684] opened 2022-02-20 22:22 UTC
```jl
julia> fig = Figure()

julia> ax = Axis(fig[1,1])
ERROR: LoadError: Plot needs to be displayed to insert additional plots
```

Is it possible for me to block until the plot is displayed so I don't get this error?

**Comment by SimonDanisch** [comment] 2022-02-21 08:53
In what circumstance do you get this error? 
I can't reproduce on GLMakie `0.5.3` and also don't see any reason why we should error like that:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/1010467/154920662-6e710605-138b-4670-8019-31508ead896f.png">

**Comment by jtrakk** [comment] 2022-02-21 09:56
[276b4fcb] WGLMakie v0.5.3
VSCode

If I run the Axis command too soon after the Figure command, I guess before the Figure is rendered on screen, it fails.

**Comment by jtrakk** [comment] 2022-05-08 18:53
![image](https://user-images.githubusercontent.com/43392409/167311166-be372d41-ef5d-4692-9643-aed4b82d11a4.png)

**Comment by jtrakk** [comment] 2022-05-10 19:41
The code is here 

https://github.com/JuliaPlots/Makie.jl/blob/master/WGLMakie/src/display.jl#L131

**Comment by asinghvi17** [comment] 2022-05-10 19:45
If you want a quick and dirty fix, just stop `fig` from displaying by doing `fig = Figure(...);`

**Comment by ffreyer** [comment] 2024-08-23 09:34
Closing as not reproducible

**Closed by ffreyer** 2024-08-23 09:34 UTC
