### ISSUE TITLE
Resolution not respected when toggling between figures

### ISSUE THREAD

**Issue by MartinOtter** [MakieOrg/Makie.jl#824] opened 2021-01-24 15:09 UTC
Take this minimal example

```
fig1 = Figure(resolution = (600,300))   # displays 600x300 figure
fig2 = Figure(resolution = (600,600))   # displays 600x600 figure
display(fig1)   # displays 600x600 figure instead of 600x300
```

This is unfortunate, when constructing several figures and toggling between them with display(..).

**Comment by jkrumbiegel** [comment] 2021-01-24 22:11
I assume you tried this with GLMakie, as I can't reproduce with CairoMakie. I think this happens when you display while a window is already open. Then the resolution of the first figure's scene is changed to the second figure's resolution through the changing of the window size. This doesn't trigger the problem for example:

```julia
fig1 = Figure(resolution = (600,300), backgroundcolor = :red) 
Figure()
fig2 = Figure(resolution = (600,600), backgroundcolor = :blue)
Figure()
fig1
```

**Comment by MartinOtter** [comment] 2021-01-25 08:02
> I assume you tried this with GLMakie, as I can't reproduce with CairoMakie. 

Yes (GLMakie, version v0.1.25 on Windows 10).

> I think this happens when you display while a window is already open. 

Yes, this is exactly the use case (a function is generating several figures and the last one is displayed. With showFigure(figureNumber) the respective figure is retrieved from a dictionary and displayed with `display(fig)` to display also the other figures).

> Then the resolution of the first figure's scene is changed to the second figure's resolution through the changing of the window size. This doesn't trigger the problem for example:

> 
> ```julia
> fig1 = Figure(resolution = (600,300), backgroundcolor = :red) 
> Figure()
> fig2 = Figure(resolution = (600,600), backgroundcolor = :blue)
> Figure()
> fig1
> ```

I tried in the REPL and in a function, but the behavior does not change.

I have already stored a copy of the resolution with every figure in my data structure. Is it possible to display an existing figure with a given (potentially new) resolution. I searched, but did not find this functionality.

**Comment by ffreyer** [comment] 2021-01-25 08:39
I think the reason this is happening is because GLMakie resizes the screen (via `global_gl_screen` in `backend_display`) before the event callbacks are disconnected (which happens on `register_callbacks`).

**Comment by ffreyer** [comment] 2024-08-22 13:25
This has been fixed in GLMakie and works in CairoMakie and WGLMakie

**Closed by ffreyer** 2024-08-22 13:25 UTC
