### ISSUE TITLE
Separate window created when using plot pane in VSCode [GLMakie]

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#2732] opened 2023-03-07 16:13 UTC
Recently, I started having to do `display` on figures to use the plot pane. But very recently, not even this could prevent a seperate window popping out. A video of the behaviour can be seen below:
https://user-images.githubusercontent.com/61620837/223480789-dfaec0a9-4cb0-4990-ac95-b75cb7a31482.mp4

How can I avoid opening the standalong window?

**Comment by jkrumbiegel** [comment] 2023-03-07 16:28
`Makie.inline!(true)`?

**Comment by SimonDanisch** [comment] 2023-03-07 16:39
Should be fixed in https://github.com/MakieOrg/Makie.jl/pull/2731

**Comment by KronosTheLate** [comment] 2023-03-08 08:04
How do I add a branch of GLMakie? I am still confused about the whole mono-repo thing:
```
(@v1.9) pkg> add https://github.com/MakieOrg/Makie.jl/tree/sd/deletions/GLMakie
     Cloning git-repo `https://github.com/MakieOrg/Makie.jl`
    Updating git-repo `https://github.com/MakieOrg/Makie.jl`
ERROR: Did not find rev sd/deletions/GLMakie in repository

```

**Comment by asinghvi17** [comment] 2023-03-08 08:06
`]add Makie#sd/deletions GLMakie#sd/deletions`

**Comment by KronosTheLate** [comment] 2023-03-10 16:01
Having tried to shutdown the julia process twice now and precompiling, I get the following precompilation error:
<details>

```
(ComputationalPhysics) pkg> precompile
Precompiling environment...
  ✗ Makie
  ✗ GLMakie
  63 dependencies successfully precompiled in 413 seconds. 310 already precompiled.

ERROR: The following 2 direct dependencies failed to precompile:

GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]

Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to "/home/dennishb/.julia/compiled/v1.9/GLMakie/jl_WsPPBh".
ERROR: LoadError: KeyError: key :deregister_callbacks not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Observables.Observable}, key::Symbol)
    @ Base ./dict.jl:484
  [2] getindex
    @ ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:91 [inlined]
  [3] getindex(x::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, key::Symbol)
    @ MakieCore ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:187
  [4] getproperty
    @ ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:78 [inlined]
  [5] on(f::Function, scene::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, observable::Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}}; update::Bool, priority::Int64)
    @ Makie ~/.julia/packages/Makie/ri2aI/src/scenes.jl:161
  [6] on
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:159 [inlined]
  [7] #map!#104
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:176 [inlined]
  [8] map!
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:171 [inlined]
  [9] #map#105
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:186 [inlined]
 [10] map(::typeof(GeometryBasics.triangle_mesh), ::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, ::Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/scenes.jl:182
 [11] plot!(plot::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/basic_recipes/poly.jl:12
 [12] plot!(scene::Makie.Scene, P::Type{MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}}, attributes::MakieCore.Attributes, input::Tuple{Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}}}, args::Observables.Observable{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/interfaces.jl:422
 [13] plot!(scene::Makie.Scene, P::Type{MakieCore.Poly}, attributes::MakieCore.Attributes, args::GeometryBasics.HyperRectangle{2, Int64}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/interfaces.jl:334
 [14] plot!
    @ ~/.julia/packages/Makie/ri2aI/src/interfaces.jl:301 [inlined]
 [15] plot(P::Type{MakieCore.Poly}, args::GeometryBasics.HyperRectangle{2, Int64}; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:strokewidth, :strokecolor, :color), Tuple{Int64, Symbol, Tuple{Symbol, Float64}}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/figureplotting.jl:48
 [16] plot
    @ ~/.julia/packages/Makie/ri2aI/src/figureplotting.jl:31 [inlined]
 [17] #poly#55
    @ ~/.julia/packages/MakieCore/LOKNz/src/recipes.jl:34 [inlined]
 [18] top-level scope
    @ ~/.julia/packages/Makie/ri2aI/src/precompiles.jl:6
 [19] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [20] include
    @ ~/.julia/packages/Makie/ri2aI/src/Makie.jl:1 [inlined]
 [21] macro expansion
    @ ~/.julia/packages/Makie/ri2aI/src/precompiles.jl:16 [inlined]
 [22] macro expansion
    @ ~/.julia/packages/SnoopPrecompile/1XXT1/src/SnoopPrecompile.jl:62 [inlined]
 [23] top-level scope
    @ ~/.julia/packages/Makie/ri2aI/src/precompiles.jl:13
 [24] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [25] include(x::String)
    @ Makie ~/.julia/packages/Makie/ri2aI/src/Makie.jl:1
 [26] top-level scope
    @ ~/.julia/packages/Makie/ri2aI/src/Makie.jl:331
 [27] include
    @ ./Base.jl:457 [inlined]
 [28] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2004
 [29] top-level scope
    @ stdin:2
in expression starting at /home/dennishb/.julia/packages/Makie/ri2aI/precompile/shared-precompile.jl:4
in expression starting at /home/dennishb/.julia/packages/Makie/ri2aI/src/precompiles.jl:12
in expression starting at /home/dennishb/.julia/packages/Makie/ri2aI/src/Makie.jl:1
in expression starting at stdin:2
ERROR: LoadError: Failed to precompile Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a] to "/home/dennishb/.julia/compiled/v1.9/Makie/jl_R28y9C".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2254
  [3] compilecache
    @ ./loading.jl:2121 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1764
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1619
  [6] macro expansion
    @ ./loading.jl:1607 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1570
  [9] include
    @ ./Base.jl:457 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2004
 [11] top-level scope
    @ stdin:2
in expression starting at /home/dennishb/.julia/packages/GLMakie/7KqRi/src/GLMakie.jl:1
in expression starting at stdin:2

Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]

Failed to precompile Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a] to "/home/dennishb/.julia/compiled/v1.9/Makie/jl_yrD7c8".
ERROR: LoadError: KeyError: key :deregister_callbacks not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Observables.Observable}, key::Symbol)
    @ Base ./dict.jl:484
  [2] getindex
    @ ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:91 [inlined]
  [3] getindex(x::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, key::Symbol)
    @ MakieCore ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:187
  [4] getproperty
    @ ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:78 [inlined]
  [5] on(f::Function, scene::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, observable::Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}}; update::Bool, priority::Int64)
    @ Makie ~/.julia/packages/Makie/ri2aI/src/scenes.jl:161
  [6] on
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:159 [inlined]
  [7] #map!#104
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:176 [inlined]
  [8] map!
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:171 [inlined]
  [9] #map#105
    @ ~/.julia/packages/Makie/ri2aI/src/scenes.jl:186 [inlined]
 [10] map(::typeof(GeometryBasics.triangle_mesh), ::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, ::Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/scenes.jl:182
 [11] plot!(plot::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/basic_recipes/poly.jl:12
 [12] plot!(scene::Makie.Scene, P::Type{MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}}, attributes::MakieCore.Attributes, input::Tuple{Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}}}, args::Observables.Observable{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/interfaces.jl:422
 [13] plot!(scene::Makie.Scene, P::Type{MakieCore.Poly}, attributes::MakieCore.Attributes, args::GeometryBasics.HyperRectangle{2, Int64}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/interfaces.jl:334
 [14] plot!
    @ ~/.julia/packages/Makie/ri2aI/src/interfaces.jl:301 [inlined]
 [15] plot(P::Type{MakieCore.Poly}, args::GeometryBasics.HyperRectangle{2, Int64}; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:strokewidth, :strokecolor, :color), Tuple{Int64, Symbol, Tuple{Symbol, Float64}}}})
    @ Makie ~/.julia/packages/Makie/ri2aI/src/figureplotting.jl:48
 [16] plot
    @ ~/.julia/packages/Makie/ri2aI/src/figureplotting.jl:31 [inlined]
 [17] #poly#55
    @ ~/.julia/packages/MakieCore/LOKNz/src/recipes.jl:34 [inlined]
 [18] top-level scope
    @ ~/.julia/packages/Makie/ri2aI/src/precompiles.jl:6
 [19] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [20] include
    @ ~/.julia/packages/Makie/ri2aI/src/Makie.jl:1 [inlined]
 [21] macro expansion
    @ ~/.julia/packages/Makie/ri2aI/src/precompiles.jl:16 [inlined]
 [22] macro expansion
    @ ~/.julia/packages/SnoopPrecompile/1XXT1/src/SnoopPrecompile.jl:62 [inlined]
 [23] top-level scope
    @ ~/.julia/packages/Makie/ri2aI/src/precompiles.jl:13
 [24] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [25] include(x::String)
    @ Makie ~/.julia/packages/Makie/ri2aI/src/Makie.jl:1
 [26] top-level scope
    @ ~/.julia/packages/Makie/ri2aI/src/Makie.jl:331
 [27] include
    @ ./Base.jl:457 [inlined]
 [28] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2004
 [29] top-level scope
    @ stdin:2
in expression starting at /home/dennishb/.julia/packages/Makie/ri2aI/precompile/shared-precompile.jl:4
in expression starting at /home/dennishb/.julia/packages/Makie/ri2aI/src/precompiles.jl:12
in expression starting at /home/dennishb/.julia/packages/Makie/ri2aI/src/Makie.jl:1
in expression starting at stdin:2
```
</details>

**Comment by SimonDanisch** [comment] 2023-03-10 18:23
You also need MakieCore#sd/deletions

**Comment by KronosTheLate** [comment] 2023-03-10 21:23
Thanks for holding my hand through it, ill give that a shot

**Comment by KronosTheLate** [comment] 2023-03-14 13:21
After an initial precompile error in a fresh temp enviroment, and doing it again in a presisten enviroment, I finally got it working! <details><summary>(Error)</summary>

```
(jl_ih4dXr) pkg> st
Status `/tmp/jl_ih4dXr/Project.toml`
  [e9467ef8] GLMakie v0.8.2 `https://github.com/MakieOrg/Makie.jl.git:GLMakie#sd/deletions`
  [ee78f7c6] Makie v0.19.2 `https://github.com/MakieOrg/Makie.jl.git#sd/deletions`
  [20f20a25] MakieCore v0.6.2 `https://github.com/MakieOrg/Makie.jl.git:MakieCore#sd/deletions`

  Activating project at `/tmp/jl_ih4dXr`

[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for MathTeXEngine [0a4f8689-d25c-4efe-a92b-7142dfc1aa53]
│   exception = Required dependency Compat [34da2185-b29b-5c13-b0c7-acf172513d20] failed to load from a cache file.
└ @ Base loading.jl:1777
ERROR: LoadError: KeyError: key :deregister_callbacks not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Observables.Observable}, key::Symbol)
    @ Base ./dict.jl:484
  [2] getindex
    @ ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:91 [inlined]
  [3] getindex(x::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, key::Symbol)
    @ MakieCore ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:187
  [4] getproperty
    @ ~/.julia/packages/MakieCore/LOKNz/src/attributes.jl:78 [inlined]
  [5] on(f::Function, scene::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, observable::Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}}; update::Bool, priority::Int64)
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/scenes.jl:161
  [6] on
    @ ~/.julia/packages/Makie/m3Gwl/src/scenes.jl:159 [inlined]
  [7] #map!#104
    @ ~/.julia/packages/Makie/m3Gwl/src/scenes.jl:176 [inlined]
  [8] map!
    @ ~/.julia/packages/Makie/m3Gwl/src/scenes.jl:171 [inlined]
  [9] #map#105
    @ ~/.julia/packages/Makie/m3Gwl/src/scenes.jl:186 [inlined]
 [10] map(::typeof(GeometryBasics.triangle_mesh), ::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}, ::Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}})
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/scenes.jl:182
 [11] plot!(plot::MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/basic_recipes/poly.jl:12
 [12] plot!(scene::Makie.Scene, P::Type{MakieCore.Poly{Tuple{GeometryBasics.HyperRectangle{2, Int64}}}}, attributes::MakieCore.Attributes, input::Tuple{Observables.Observable{GeometryBasics.HyperRectangle{2, Int64}}}, args::Observables.Observable{Tuple{GeometryBasics.HyperRectangle{2, Int64}}})
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/interfaces.jl:422
 [13] plot!(scene::Makie.Scene, P::Type{MakieCore.Poly}, attributes::MakieCore.Attributes, args::GeometryBasics.HyperRectangle{2, Int64}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/interfaces.jl:334
 [14] plot!
    @ ~/.julia/packages/Makie/m3Gwl/src/interfaces.jl:301 [inlined]
 [15] plot(P::Type{MakieCore.Poly}, args::GeometryBasics.HyperRectangle{2, Int64}; axis::NamedTuple{(), Tuple{}}, figure::NamedTuple{(), Tuple{}}, kw_attributes::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:strokewidth, :strokecolor, :color), Tuple{Int64, Symbol, Tuple{Symbol, Float64}}}})
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/figureplotting.jl:48
 [16] plot
    @ ~/.julia/packages/Makie/m3Gwl/src/figureplotting.jl:31 [inlined]
 [17] #poly#55
    @ ~/.julia/packages/MakieCore/LOKNz/src/recipes.jl:34 [inlined]
 [18] top-level scope
    @ ~/.julia/packages/Makie/m3Gwl/src/precompiles.jl:6
 [19] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [20] include
    @ ~/.julia/packages/Makie/m3Gwl/src/Makie.jl:1 [inlined]
 [21] macro expansion
    @ ~/.julia/packages/Makie/m3Gwl/src/precompiles.jl:16 [inlined]
 [22] macro expansion
    @ ~/.julia/packages/SnoopPrecompile/1XXT1/src/SnoopPrecompile.jl:62 [inlined]
 [23] top-level scope
    @ ~/.julia/packages/Makie/m3Gwl/src/precompiles.jl:13
 [24] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [25] include(x::String)
    @ Makie ~/.julia/packages/Makie/m3Gwl/src/Makie.jl:1
 [26] top-level scope
    @ ~/.julia/packages/Makie/m3Gwl/src/Makie.jl:331
 [27] include
    @ ./Base.jl:457 [inlined]
 [28] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2004
 [29] top-level scope
    @ stdin:2
in expression starting at /home/dennishb/.julia/packages/Makie/m3Gwl/precompile/shared-precompile.jl:4
in expression starting at /home/dennishb/.julia/packages/Makie/m3Gwl/src/precompiles.jl:12
in expression starting at /home/dennishb/.julia/packages/Makie/m3Gwl/src/Makie.jl:1
in expression starting at stdin:2
ERROR: LoadError: Failed to precompile Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a] to "/home/dennishb/.julia/compiled/v1.9/Makie/jl_aVliHj".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2254
  [3] compilecache
    @ ./loading.jl:2121 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1764
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1619
  [6] macro expansion
    @ ./loading.jl:1607 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1570
  [9] include
    @ ./Base.jl:457 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2004
 [11] top-level scope
    @ stdin:2
in expression starting at /home/dennishb/.julia/packages/GLMakie/7KqRi/src/GLMakie.jl:1
in expression starting at stdin:2
ERROR: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to "/home/dennishb/.julia/compiled/v1.9/GLMakie/jl_JQljic".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2254
  [3] compilecache
    @ ./loading.jl:2121 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1764
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1619
  [6] macro expansion
    @ ./loading.jl:1607 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1570
  [9] eval
    @ ./boot.jl:370 [inlined]
 [10] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1858
 [11] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
 [12] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
 [13] inlineeval(m::Module, code::String, code_line::Int64, code_column::Int64, file::String; softscope::Bool)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/eval.jl:233
 [14] (::VSCodeServer.var"#66#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/eval.jl:157
 [15] withpath(f::VSCodeServer.var"#66#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/repl.jl:249
 [16] (::VSCodeServer.var"#65#69"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/eval.jl:155
 [17] hideprompt(f::VSCodeServer.var"#65#69"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/repl.jl:38
 [18] (::VSCodeServer.var"#64#68"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/eval.jl:126
 [19] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging ./logging.jl:514
 [20] with_logger
    @ ./logging.jl:626 [inlined]
 [21] (::VSCodeServer.var"#63#67"{VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/eval.jl:225
 [22] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [23] invokelatest(::Any)
    @ Base ./essentials.jl:813
 [24] macro expansion
    @ ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/VSCodeServer/src/eval.jl:34 [inlined]
 [25] (::VSCodeServer.var"#61#62")()
    @ VSCodeServer ./task.jl:514
```
</details>

And I can confirm - the window now correctly used the plot pane.
I can also confirm that I get the same behaviour when I run `current_figure()` in script (by command in picture below)
![image](https://user-images.githubusercontent.com/61620837/225013235-49e9d54c-5664-41b6-9927-018599999c99.png)
, and when I run it in the integrated REPL. Also, using `Makie.inline!()` toggles as expected in both script and REPL. This is the first time I have gotten the expected behaviour in all my time using Makie, and it feels great :D

**Comment by jkrumbiegel** [comment] 2023-03-14 15:27
There's nothing like fixing bugs people have gotten used to for years..

**Comment by SimonDanisch** [comment] 2023-03-14 21:06
Only on that PR?

**Comment by KronosTheLate** [comment] 2023-03-15 11:09
Yhea. It also scaled just fine when I tried to reproduce, but I am pretty sure it has neven happened when not on the sd/deletions branch

**Closed** 2023-03-15 12:01 UTC

**Comment by SimonDanisch** [comment] 2023-03-15 12:17
Any idea how to reproduce it?

**Comment by KronosTheLate** [comment] 2023-03-21 08:39
No, unfortunatly not. It mostly seems to behave, as it was a one-off observation.

A larger problem is that after calling `empty!` on a figure, when I add elements to the figure, it does not respond. I have reproduced this consistently several times now, no exceptions, on the `sd/deletions` branch. Do you get the same behaviour?

**Comment by SimonDanisch** [comment] 2023-03-21 08:45
Can you open an issue with an MWE & versions used? Best use master, since we fixed a lot of those problems there...

**Comment by KronosTheLate** [comment] 2023-03-21 09:34
Sure. Thanks for you work.
