### ISSUE TITLE
Image does not scale properly in the window after rotating the image 

### ISSUE THREAD

**Issue by logankilpatrick** [MakieOrg/Makie.jl#397] opened 2019-10-11 11:21 UTC
Has there been any further dev on this? I remember @asinghvi17 saying it was sort of fixed in a branch somewhere but that it wasn’t done yet.

**Comment by SimonDanisch** [comment] 2019-10-13 10:40
Can you please post a short code that reproduces the behavior?

**Comment by logankilpatrick** [comment] 2019-10-13 17:21
I guess: 

```
using Makie

image1 = image(AbstractPlotting.logo(), scale_plot = false)
rotate!(image1, 0.5pi)

 holder = vbox(
     image1,
     image(rand(100, 500), scale_plot = false),
 )
 
 display(holder)
```

will show the issue. But it's better seen here where the energy plot on the bottom right is at it's full size since it hasnt been rotated, but the rest are all sized weirdly since they were rotated: 

![issueWithMakie](https://user-images.githubusercontent.com/35577566/66719319-33c9ab80-edbc-11e9-876e-c7ca036f62ba.gif)

**Comment by logankilpatrick** [comment] 2019-10-22 14:54
@SimonDanisch how can I get my makie plots on the left to be sized the same like they are on the Plot's pane on the right?

**Comment by logankilpatrick** [comment] 2019-10-28 15:41
The essence of what I want: the plot/sub-scene to automatically take up all available space. You can see the difference in the two sizings above. I am looking for the uniform size that plots.jl gives. @asinghvi17

**Comment by asinghvi17** [comment] 2019-10-28 18:52
Ah, that would need better layouting support.  Right now it's sort of patched together AFAIU...there is a layout constraint solver, we just have to integrate it with axes and all that.

**Comment by SimonDanisch** [comment] 2019-11-04 23:15
@jkrumbiegel and I are trying to figure this out atm!

**Comment by ffreyer** [comment] 2024-08-21 18:10
Closing this as outdated and at least partially fixed since the infrastructure is better at resizing things now. There may still be some issues with boundingboxes picking up on rotation but that's not the case with Axis atm.

**Closed by ffreyer** 2024-08-21 18:10 UTC
