### ISSUE TITLE
GLMakie screens resize after being updated?

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#2063] opened 2022-06-16 14:15 UTC
Consider the following MWE:
```julia
using Makie, GLMakie
using Makie.GeometryBasics

begin
       # this must be larger than the maximal size of a GLMakie window in at least one dimension
       fig = Figure(resolution = (2500, 2500)) 
       screen = display(fig)
       @show GeometryBasics.widths(screen)
       fig.scene.backgroundcolor[] = Makie.to_color(:black)
       @show GeometryBasics.widths(screen)
end
```
This returns:
```julia
GeometryBasics.widths(screen) = (2500, 2500)
GeometryBasics.widths(screen) = (2500, 1942)
```

showing that the screen renders fine, but then resizes itself when some aspect of the screen is updated.  This is a regression from previous behaviour since GLMakie was able to successfully render scenes whose resolution was larger than the display size.

This feature is really useful if one is rendering a scene which needs to be analysed as an image, for example simulating the diffraction pattern of a laser shining through a chamber containing some simulated organism.

**Comment by SimonDanisch** [comment] 2022-06-17 09:37
Are you sure that this is a regression? I remember that this issue popped up ages ago, and it's pretty much not fixable since it's the window manager who resizes the window... Maybe we can render these still by hiding the window, that'd be worth a try...

**Comment by asinghvi17** [comment] 2022-06-17 11:53
Yeah, the odd thing is that this was working fine for the 3000x3000 px volume plots I was rendering in #2061, which was then dumping the rendered image into a PNG to debug.  I could see that the Makie window was larger than the screen then.

Is there a good way to hide the window programmatically?  I can try that out and report back.

**Comment by asinghvi17** [comment] 2022-06-18 03:42
Specifically new behaviour after #1771.  I will try that out though, thanks!

**Comment by ffreyer** [comment] 2024-08-23 11:34
@SimonDanisch Is this something we are planning on fixing or is `visible = false` / `save(size = ...)` / `record(size = ...)` the way to handle this?

**Comment by SimonDanisch** [comment] 2024-08-23 11:37
As far as Im concerned, the windows window manager does this and I don't think there's any hack around it besides colorbuffer and friends

**Comment by ffreyer** [comment] 2024-08-23 12:08
Ok, closing this with the suggestion of using `visible = false`, `save` or `record` then

**Closed by ffreyer** 2024-08-23 12:08 UTC
Labels: maybe wontfix, GLMakie, regression
