### ISSUE TITLE
Make + `vline` compatible with `DateTime`

### ISSUE THREAD

**Issue by martincornejo** [MakieOrg/Makie.jl#4256] opened 2024-08-26 17:18 UTC
Currently the following does not work:

```julia
t = DateTime("2024-01-01"):Minute(1):DateTime("2024-01-02")
x = randn(length(t)) |> cumsum

fig, ax = lines(t, x)
vline!(ax, DateTime("2024-01-01T12:00")) # ERROR: MethodError: no method matching vline!(::Axis, ::DateTime)
```

**Comment by SimonDanisch** [comment] 2024-08-26 17:34
Duplicate of: https://github.com/MakieOrg/Makie.jl/issues/4119

**Closed by SimonDanisch** 2024-08-26 17:34 UTC
Labels: enhancement
