### ISSUE TITLE
Support for mutating plot object in `convert_attributes`

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#508] opened 2020-03-04 19:31 UTC
Would allow us to do stuff like this:

https://github.com/JuliaPlots/GraphRecipes.jl/blob/cd3ccc880f425d1b2df7f46a0874252ed08b437a/src/graphs.jl#L285-L289

**Comment by ffreyer** [comment] 2024-08-21 19:30
As far as I understand `convert_arguments()`  is separated from the plot by design. If you have attributes that influence conversion you can apply them via `used_attributes`, which will consume them, or you can just handle the conversion in `plot!(::MyRecipe)`.

Closing as wont-fix

**Closed by ffreyer** 2024-08-21 19:30 UTC
Labels: enhancement, Makie, recipes

**Comment by asinghvi17** [comment] 2024-08-22 03:01
I'd say this was addressed by `PlotSpec`/`PlotList` and used_attributes, yes.
