### ISSUE TITLE
"Non-mutating" functions do mutate

### ISSUE THREAD

**Issue by jtrakk** [MakieOrg/Makie.jl#887] opened 2021-03-17 19:41 UTC
[The docs](http://makie.juliaplots.org/stable/plot_method_signatures.html#Non-Mutating) describe the `lines` function as "non-mutating", but I think it does mutate the first argument. Otherwise 

```jl
lines(fig[2, 1], cumsum(randn(1000)),
    axis = (xlabel = "Time (sec)", ylabel = "Baz"),
    color = :blue)
```

, without assigning the return value to a variable, wouldn't do anything.

Therefore I think "explicit" vs "implicit" are better descriptors than "non-mutating" and "mutating". 

But then, if they're all mutating, shouldn't they both be called `lines!()`, and distinguished by the type of the first argument, rather than having a function `lines(ax)` whose name indicates non-mutation?

That being said, a purely functional API would be very interesting.

**Comment by jkrumbiegel** [comment] 2021-03-17 20:23
Yeah that's just imprecise language, mainly it means "with and without !". It's because a plot always needs a container (figure, scene, axis,...). And either the function creates a new container (non-mutating) or it adds to an existing one (mutating).

**Comment by jtrakk** [comment] 2021-03-17 20:52
It could be like

```jl
Figure([Lines(cumsum(randn(1000)))])
```

so the container knows about the plot but the plot doesn't need to know about the container.

**Comment by ffreyer** [comment] 2024-08-22 14:20
Closing this as it is as intended and docs for it exist

**Closed by ffreyer** 2024-08-22 14:20 UTC
