### ISSUE TITLE
Slider updates not reflected graphically

### ISSUE THREAD

**Issue by yha** [MakieOrg/Makie.jl#794] opened 2020-12-24 13:02 UTC
When an `LSlider`'s `value` is updated programatically, it doesn't show. Here you can see the text updating when the button is clicked, but not the slider:
```
scene, layout = layoutscene()
btn = layout[1,1] = LButton(scene)
sl = layout[2,1] = LSlider(scene; width=500)
txt = layout[3,1] = LText(scene)
on(btn.clicks) do _
    sl.value[] = 10
end
on(sl.value) do n
    txt.text[] = string(n)
end

scene
```

**Comment by yha** [comment] 2020-12-24 15:30
Looks like the same happens with text boxes:
```

scene,layout = layoutscene()
btn = layout[1,1] = LButton(scene)
tb = layout[2,1] = LTextbox(scene; width=500)
txt = layout[3,1] = LText(scene)
on(btn.clicks) do _
    tb.stored_string[] = "foo"
end
on(tb.stored_string) do n
    txt.text[] = string(n)
end

scene
```

**Comment by jkrumbiegel** [comment] 2020-12-24 15:36
The problem is that for some observables that are outputs and inputs semantically, it's really hard to set them up that way. `value` is an output of the slider, it doesn't affect the internal state of the slider if you change it because it's not backwards connected. Same with the textbox. The slider has the method `set_close_to!` to set the value (problem with setting exactly is that the slider's range might often not contain the exact value specified). For textboxes it's `set!(textbox, string)` currently https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/makielayout/lobjects/ltextbox.jl#L308-L320

**Comment by yha** [comment] 2020-12-24 16:15
I see, that does make sense. Perhaps the attribute docs should mention how to set them. I'll try putting together a docs PR.

> Same principle with the textbox. For textboxes it's `set!(textbox, string)` currently https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/makielayout/lobjects/ltextbox.jl#L308-L320

I see that this is not exported, which makes sense for a very general name like `set!`. Maybe it would make sense to add a `setindex!` method for that, so the text can be set as `textbox[] = string`?

**Comment by jkrumbiegel** [comment] 2020-12-25 10:09
Yeah `set!` is too generic while not being a Base method, maybe there's a better possibility there. I didn't finish that part of the LTextbox interface yet. I'll think about setindex, although I usually prefer more obvious function interfaces

**Comment by bjarthur** [comment] 2023-06-29 22:17
maybe just add "see also set_close_to!" in the docstring for Slider?

**Comment by bjarthur** [comment] 2023-06-29 22:18
the docstring for `set_close_to!` could also use a function signature

**Comment by bjarthur** [comment] 2023-06-29 22:35
`set_close_to!` updates the display for me!

but is there a way to update the value of a slider programmatically, have the display updated, and **not** trigger listeners?  the [docs](https://docs.makie.org/dev/documentation/nodes/index.html#problems_with_synchronous_updates) say to set the `.val` to not trigger listeners, but that also doesn't update the display.

**Comment by jkrumbiegel** [comment] 2023-06-30 05:42
No, the slider will always keep its observables in sync. But you can block the proliferation of updates after the slider is updated, for example by attaching another observable that also listens to a Bool or an if condition in some other place where it makes sense

**Comment by bjarthur** [comment] 2024-03-06 00:25
as [posted](https://discourse.julialang.org/t/makie-jl-textbox/101600/4?u=bjarthur) on discourse, `set!` works, but as they're not exported you have to use `Makie.set!`.  notably, `GLMakie.set!` does *not* work, which is what i tried before i posted this comment.

should you decide to export at some point, maybe `setproperty!` or `setfield!` ?

**Comment by ffreyer** [comment] 2024-08-22 12:38
Closing this as the original problem is solved. I suggest moving discussions about other Blocks into a new if needed https://github.com/MakieOrg/Makie.jl/discussions/categories/q-a post

**Closed by ffreyer** 2024-08-22 12:38 UTC
