### ISSUE TITLE
`stephist!` doesn't support `direction=:x` keyword argument

### ISSUE THREAD

**Issue by GlenHertz** [MakieOrg/Makie.jl#3295] opened 2023-10-13 15:17 UTC
- [x] are you running newest version (version from docs) ? (`sd/beta-20`)
- [x] can you reproduce the bug with a fresh environment ? (`yes`)
- [x] What platform + GPU are you on? (`WGLMakie on M1 Mac`)

I'm trying to  use `stephist!(plt, vals; direction=:x, strokewidth, color)` but the `direction` is not supported.

**Comment by ffreyer** [comment] 2024-08-26 15:02
Closing as duplicate of #2834

**Closed by ffreyer** 2024-08-26 15:02 UTC
Labels: bug
