### ISSUE TITLE
Alpha modifier

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#3466] opened 2023-12-13 15:59 UTC
I am often in the situation where I just want to add some alpha (transparency) to a plot, without making changes to colors. So I would like to use the default colours, or one specified with `Cycled`, but with some alpha != 1.. However, I have been unable to find a way to do this without manually specifying a color.

Perhaps it would be feasable to add field "alpha" to `Cycled`? It could then be `Cycled(1, 0.5)`, analogus to `(:black, 0.5)`.

**Comment by KronosTheLate** [comment] 2023-12-13 16:05
My band-aid fix ended up being `color=Makie.wong_colors(alpha)[i]`, which worked well. But it uses a non-exported function, and it quite verbose, and so it feels hacky.

**Comment by jkrumbiegel** [comment] 2023-12-13 17:02
nowadays a lot of plot objects take an `alpha` keyword, does that help?

**Comment by KronosTheLate** [comment] 2023-12-13 17:05
Oh wow, yes! I did not realize that I could change it for the plot object like that, this is exactly what I was looking for.

I guess the fix then is just to document this in [the docs](https://docs.makie.org/stable/explanations/transparency/), and possibly at the top. Definitively before the "problems with transparency" at least. I imagine that this will be the most ergonomic way for most poeople to quickly change the transparency.

**Comment by ffreyer** [comment] 2024-08-26 20:22
Closing as duplicate of #1629

**Closed by ffreyer** 2024-08-26 20:22 UTC
Labels: enhancement
