### ISSUE TITLE
GLMakie with PackageCompiler.jl breaks display of numbers

### ISSUE THREAD

**Issue by AndiMD** [MakieOrg/Makie.jl#2521] opened 2022-12-25 18:36 UTC
Hi,
when I use a sysimage with GLMakie created with PackageCompiler.jl, the dots in floating point numbers show as grey boxes. Not sure if this is an issue with PackageCompiler, Makie, or my recent update from Julia 1.8.3 to 1.8.4.

![image](https://user-images.githubusercontent.com/24719218/209478649-8c7d0dea-da7e-4218-9c5c-16a29a3978cc.png)

Makie v0.19.0
GLMakie v0.8.0
```
Julia Version 1.8.4
Commit 00177ebc4fc (2022-12-23 21:32 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 12 on 24 virtual cores
Environment:
  LD_LIBRARY_PATH = :/usr/local/cuda-11.0/lib64
  JULIA_NUM_THREADS = 12
  JULIA_EDITOR = vim
```

**Comment by SimonDanisch** [comment] 2022-12-25 20:13
Can you try master?

**Comment by AndiMD** [comment] 2022-12-25 21:56
Master works, thank you.
[e9467ef8] GLMakie v0.8.0 `https://github.com/MakieOrg/Makie.jl.git:GLMakie#master`

**Comment by SimonDanisch** [comment] 2022-12-29 14:16
Great! This is a duplicate of https://github.com/MakieOrg/Makie.jl/issues/2480

**Closed by SimonDanisch** 2022-12-29 14:16 UTC
