### ISSUE TITLE
WGLMakie on mobile

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#2646] opened 2023-02-02 08:02 UTC
I tried a WGLMakie plot served through JSServe on mobile, and it seemed to work!  It did have a few issues which I felt could be clarified, though.

1. Is it possible to detect the resolution and physical dimensions of the device (in inches or cm) on which the plot is being rendered, and set a theme accordingly?  For example, on mobile I may want slider buttons to be larger in order to make it easier to use with fingers.  
2. Similarly, zooming and other behaviours would have to be adapted for touchscreen - is this possible?  e.g. I may want single finger drag to move, but two finger drag to zoom, may also want to enable pinch zooming, etc.  A lot of this seems to be possible on Mac touchpad, so I guess it would just be a matter of adapting it to web.
3. Is it possible to "ship" a data inspector along with the plot, so it can operate locally instead of calling back to the server for information? 
4. Can interactive utilities like datainspector be used in a "serialized" plot loaded from HTML, with no connection to a Julia server?  This would be the ideal scenario but it may be impossible/unlikely - unless coded up specifically for WGLMakie in JS.  That might be OK as well.

**Comment by SimonDanisch** [comment] 2023-02-02 09:13
There are offline tooltip you can use:
https://docs.makie.org/stable/documentation/backends/wglmakie/index.html#offline_tooltip

1 + 2 are certainly possible, just need some work ;)

**Comment by asinghvi17** [comment] 2023-02-02 09:55
Nice! This looks pretty promising - will pitch it for sure.  I guess the only thing that really needs work is theming for different devices and getting HTML output which looks good.

**Comment by SimonDanisch** [comment] 2023-02-02 10:09
I guess that's one of the main problems here, that I'm not a web developer and therefore will need to learn & google those things myself ;)
For 1, I think we should look into tailwind, and figure out a few reactive classes that we can throw into `TailwindDashboard` to make things work better.
For 2, I guess we'll need to figure out some way to change the makie camera defaults from JS.... To really make this nice, we'll need to port the camera + part of the axis code to JS anyways...

**Comment by asinghvi17** [comment] 2023-02-02 11:58
I guess that I was thinking you could have several pre-rendered HTML files, and the server just picks one to send based on your device's display scale.  I'm not too sure how we could get Makie text rendering working with CSS though :D

**Comment by SimonDanisch** [comment] 2023-02-02 12:00
I don't think that's how one would solve this problem in the world of modern HTML + CSS^^

**Comment by asinghvi17** [comment] 2023-02-05 09:55
I guess if the axis were to be rendered in JS, that would be possible...guess there would have to be some sort of specialized rendering pipeline, which takes in a Figure instead of a Scene.

**Comment by asinghvi17** [comment] 2023-02-06 08:25
Found a nice example recently (from the Guardian).  Basically, this is what I want to implement with serverless WGLMakie:

https://user-images.githubusercontent.com/32143268/216918948-8c5a5ab2-aaa3-452e-8653-90506694dc83.mp4

**Comment by asinghvi17** [comment] 2023-02-07 12:19
Looks like three.js's [OrbitControls](https://threejs.org/docs/#examples/en/controls/OrbitControls) could be used when detaching a 3D scene to enable touch, since it allows for touch interactions natively.  Is there a particular reason we don't currently use that?  Looking at the code, it seems we've rolled our own mouse controller.

**Comment by ffreyer** [comment] 2024-08-24 14:36
Closing as duplicate of #4219

**Closed by ffreyer** 2024-08-24 14:36 UTC
Labels: WGLMakie, Integration
