### ISSUE TITLE
Volume don't render absorption for negative numbers

### ISSUE THREAD

**Issue by knuds** [MakieOrg/Makie.jl#3233] opened 2023-09-15 09:46 UTC
- [yes] are you running newest version (version from docs) ?
- [yes] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [ Ubuntu 22.04.3 LTS + Mesa Intel® UHD Graphics (TGL GT2)] What platform + GPU are you on?

The following code shows the bug, negative values don't show op.
And if you subtract the minimum to get all positive numbers, there is a problem with absorption.
You can see it if you watch the second plot along the (z=0) plane. (I didn't know how to adjust the eye position on the plot, sorry)
I assume that absorption is scaled with the data instead of abs() on the data, and that the problem.
```julia
using GLMakie

xs, ys, zs = [-10:0.1:10 for d in range(1,3)]

vol = [z/sqrt(x^2+y^2+z^2+0.0001) for x in xs, y in xs, z in zs]

min,max=extrema(vol)

f=volume(xs,ys,zs,vol; colormap=:redsblues, colorrange=(min,max))

save("volmwe1.png",f)

vol=vol.-min

g=volume(xs,ys,zs,vol; colormap=:redsblues, colorrange=(0,max-min))

save("volmwe2.png",g)
```
![volmwe1](https://github.com/MakieOrg/Makie.jl/assets/607447/e5a9589f-6453-4ca5-ae01-abdff79ea795)
![volmwe2](https://github.com/MakieOrg/Makie.jl/assets/607447/5f2d1d71-0585-41f1-b0fb-531fc7ef01d3)

**Comment by knuds** [comment] 2023-09-18 12:57
Adding `algorithm=:absorption` solves the problem for negativ numbers.

**Comment by ffreyer** [comment] 2024-08-26 14:30
Closing as duplicate of #1780

**Closed by ffreyer** 2024-08-26 14:30 UTC
Labels: bug, GLMakie, WGLMakie, rendering, volume, colors
