### ISSUE TITLE
Axis legend for PolarAxis

### ISSUE THREAD

**Issue by jariji** [MakieOrg/Makie.jl#4077] opened 2024-08-01 04:59 UTC
`axislegend` doesn't work for `PolarAxis`:

```jl
julia> let fig = Figure()
           ax = Axis(fig[1,1])
           lines!(ax, rand(5), rand(5); label="hello")
           axislegend(ax)
           fig
       end # ok 

julia> let fig = Figure()
           ax = PolarAxis(fig[1,1])
           lines!(ax, rand(5), rand(5); label="hello")
           axislegend(ax)
           fig
       end
ERROR: MethodError: no method matching initialize_block!(::Legend, ::PolarAxis)
```

**Comment by ffreyer** [comment] 2024-08-28 18:38
Closing as duplicate of #3110

**Closed by ffreyer** 2024-08-28 18:38 UTC
Labels: enhancement
