### ISSUE TITLE
Unable to change line colour with `ecdfplot!`

### ISSUE THREAD

**Issue by chris-revell** [MakieOrg/Makie.jl#3933] opened 2024-06-05 12:29 UTC
```
fig = Figure(size=(1000,1000))
ax = Axis(fig[1,1])
ecdfplot!(ax, data1; color=:red, label="One")
ecdfplot!(ax, data2; color=:green, label="Two")
axislegend(ax)
display(fig)
```
Code of the above form produces two blue lines, and throws the error `ERROR: KeyError: key :label not found` for the `axislegend`
 call. 
Julia Version 1.10.3
CairoMakie v0.12.2
Makie v0.21.2

**Comment by nchisholm** [comment] 2024-06-30 15:19
It seems #3898 is the same issue and I tried to give a workaround there. Basically, you can use `ecdf` from `StatsBase` and `stairs`, like Makie does internally, but evaluate the ecdf function at the desired points manually and plot those.  If you instead pass the `ECDF` object itself as a function to `stairs`, the bug is triggered.

**Comment by chris-revell** [comment] 2024-07-01 11:06
Thanks, that's useful.

**Comment by SimonDanisch** [comment] 2024-08-27 14:11
This got fixed in https://github.com/MakieOrg/Makie.jl/pull/4079

**Closed by SimonDanisch** 2024-08-27 14:11 UTC
Labels: bug, Makie

**Comment by SimonDanisch** [comment] 2024-08-27 15:25
Uhm, I just looked at the MWE ... Not sure why the title of the issue and the described problem in the  MWE don't match, but this seemed to be about axislegend.
There is an open issue about the line color, so otherwise this would be closed as a duplicate of https://github.com/MakieOrg/Makie.jl/issues/3898.
