### ISSUE TITLE
2D slices in Axis3 not rendered properly in CairoMakie

### ISSUE THREAD

**Issue by davidschlegel** [MakieOrg/Makie.jl#2983] opened 2023-05-26 13:32 UTC
I would like to plot 2D slices as planes in an ` Axis3` object.

If I do e.g. with `GLMakie` the following:

```julia
fig = Figure()
ax1 = Axis3(fig[1,1],
limits = (0, 10, 0, 10, 0, 10)
)

xrange = range(0, 10, length = 101)
yrange = range(0, 10, length = 101)
zrange = range(0, 10, length = 101)

#test 
heatmap!(ax1, xrange, yrange, randn(101, 101),
        colormap = :viridis,
        space = :data,
        transformation=(:xy, 0)
)

heatmap!(ax1, xrange, zrange, randn(101, 101),
         colormap = :viridis,
         space = :data,
         transformation=(:xz, 0)
)

heatmap!(ax1, yrange, zrange, randn(101, 101),
         colormap = :viridis,
         space = :data,
         transformation=(:yz, 0)
)
```
I obtain the correct result:
![2DslicestestGL](https://github.com/MakieOrg/Makie.jl/assets/24460573/4d27da71-35bb-4514-87dc-9cd7395ecdac)

However, with `CairoMakie`, I get
![2Dslicestest](https://github.com/MakieOrg/Makie.jl/assets/24460573/9b483c79-32e0-48e4-8e7a-97be403815fb)

Is there a specific difference in this regard?

version used for these plots:
CairoMakie v0.10.4
GLMakie v0.8.4

**Comment by ffreyer** [comment] 2023-05-26 13:39
Duplicate of #2889

**Closed by ffreyer** 2023-05-26 13:39 UTC

**Comment by davidschlegel** [comment] 2023-05-26 13:41
Sorry for my ignorance, but good to know that you are working on it!
