### ISSUE TITLE
GLMakie window is closed and re-opened upon rendering of a new plot

### ISSUE THREAD

**Issue by lassepe** [MakieOrg/Makie.jl#2453] opened 2022-11-28 08:16 UTC
As of 9f767a36640369950d662377579dca5d0d0c52ba (according to git bisect), the GLMakie rendering window is closed and re-opened between rendering of plots. On i3, this has the side-effect that the window pops up in a new container and "forgets" it's previous size.

I usually mark the GL window as floating and place it over my REPL but now that it reopens every time, that no longer works. I am not sure whether this change of behavior is also visible with other window managers.

**Comment by SimonDanisch** [comment] 2022-11-28 09:43
Could you try master? I might have just fixed a related issue... Otherwise, can you give more details about how to reproduce this?

**Comment by lassepe** [comment] 2022-11-28 10:40
I did try master when I bisected this so the problem still persists. On i3, the way to reproduce this this would be to

1. `using GLMakie; scatter([0])` to open a window with a scatter plot
2. `scatter([0])` to generate a new scatter plot
  - observed behavior on master (since 9f767a3): the window is closed and a new window is opened instead
  - expected behavior (as observed before 9f767a3): the plot is rendered into the same window without re-opening.

Unfortunately, I have no non-i3 machine available right now so I cannot test if those steps reproduce the issue on other WMs as well.

**Comment by SimonDanisch** [comment] 2022-11-28 10:51
![screen](https://user-images.githubusercontent.com/1010467/204259769-df9146cf-ac37-4054-8fdb-53fae78c3731.gif)
is this the behavior you expect? If yes, I guess I can't reproduce this :(

**Comment by lassepe** [comment] 2022-11-28 14:21
Yes, this is the behavior I had hoped to see but that's not what happens on i3.
![Peek 2022-11-28 15-16](https://user-images.githubusercontent.com/10076790/204300820-ac588e32-7b8d-4a61-b145-41802165fbe1.gif)

In fact, I spun up a VM with Ubuntu 20.04 to check this and I'm seeing the same problem there: the window closes for a brief moment and reopens in a different place:


![Peek 2022-11-28 15-19](https://user-images.githubusercontent.com/10076790/204300765-1d1f0d2e-d63a-481b-8ddc-b0452bb294a1.gif)

**Comment by Sleort** [comment] 2022-12-20 21:30
FWIW I'm experiencing the same issue on Ubuntu 20.04...

**Comment by lassepe** [comment] 2023-01-01 18:47
I dug a little bit into this today and I noticed that the issue is symptomatically fixed if I comment out this line:

https://github.com/MakieOrg/Makie.jl/blob/0cbae0437a60e5c1a41c1114aabf8a1440e324a9/GLMakie/src/screen.jl#L564

But I am not sure whether that workaround has other undesirable side-effects since I'm not familiar with the Makie code base. Any ideas, @SimonDanisch?

**Comment by SimonDanisch** [comment] 2023-01-01 18:51
Ah yeah, actually, I noticed this bug too at some point and got to this line, and wanted to fix it, but it was a bit more complicated then I hoped for, so I haven't come around to fixing it yet -.-

**Comment by SimonDanisch** [comment] 2023-04-27 10:09
It's really weird that changing the screen visibility changes the position of the window on linux.
I'm not sure if we can fix this within makie, since hiding the window is already the most non destructive way of "closing" a window.
From you bisect I take, that it was working before and can't be due to a linux update?
So I guess there must be some way, but since hiding the window isn't supposed to change the window position it's hard to tell what needs reverting.
I did add some more debug output, so if you add:
```julia
using GLMakie
ENV["JULIA_DEBUG"] = GLMakie
```
You should get some infos about when screens are getting re-used etc...

**Comment by knuesel** [comment] 2023-12-22 16:45
I have the same issue with the tiling windows manager in Pop Os 22.04. It kind of makes sense if the window gets hidden:

Each tile can contain a stack of windows (only the one on top of the stack is shown). When the plot window is hidden, the tiling window manager will use the space for the other windows: 

1. If there's another window in the stack it will be shown instead of the plot.
1. If there's nothing else in the stack, the tile space will be allocated to other tile(s), i.e. other visible windows will be resized automatically to take advantage of the newly available space.

So in case 1 the window manager could remember in which stack the plot window was shown and keep it there, but this wouldn't help with case 2. And that's the usual case, and the worst looking: whenever I run a new plot command the window layout changes to use the space freed by the hidden window, and then immediately afterwards it changes again to insert the unhidden window in a new tile (it's rather annoying).

Is it really necessary to hide the window if it's getting shown again right afterwards? Is this to avoid some artifacts?

**Comment by knuesel** [comment] 2023-12-22 16:53
To be clear, the most annoying is when doing e.g. `scatter(1:5)` and then later `scatter(1:5)` again: the second call makes the window disapear, the layout update, then the window appear again in a new tile (typically in a different place).

It's much better if I do this instead:

```julia
using GLMakie

scr = GLMakie.Screen()
display(scr, scatter(1:5))

# then later
empty!(scr)
display(scr, scatter(1:5))
```

It's still a bit ugly because the second display resizes the window temporarily to the size set by Makie, before the tiling window manager resizes it again to the tile size. But at least it stays in the same tile.

**Comment by jmert** [comment] 2024-05-21 19:48
I've been annoyed by this problem as well — Arch Linux, Gnome 46 desktop environment. This is especially bad in my experience because the window always reappears near the top-left corner of whichever monitor my mouse is on, so it's hard to keep the figure on one monitor while I work on code on the other.

I can get the behavior I expect if I apply the following patch:
```diff
diff --git a/GLMakie/src/screen.jl b/GLMakie/src/screen.jl
index 0bab3fd24..2d2e730f2 100644
--- a/GLMakie/src/screen.jl
+++ b/GLMakie/src/screen.jl
@@ -322,7 +322,7 @@ function singleton_screen(debugging::Bool)
     if !isempty(SINGLETON_SCREEN)
         @debug("reusing singleton screen")
         screen = SINGLETON_SCREEN[1]
-        close(screen; reuse=false)
+        empty!(screen)
     else
         @debug("new singleton screen")
         # reuse=false, because we "manually" re-use the singleton screen!
```

The figure size still changes to match the theme default (i.e. if the window was manually resized), but it gets rid of problem with the figure disappearing and then reappearing in a different location and taking focus.

**Closed** 2024-12-16 18:41 UTC
Labels: enhancement, GLMakie
