### ISSUE TITLE
(Possibly) incoherent semantics for `ymax`and `ymin`  in `vlines`! 

### ISSUE THREAD

**Issue by lfenzo** [MakieOrg/Makie.jl#1831] opened 2022-04-21 19:27 UTC
I was struggling to get a plot done with CairoMakie until figured out that `ymax` and `ymin` in `vlines!` actually correspond to the percentage of the dimension (in the case of `vlines!`, the vertical space) that the vertical line will occupy in the axis. The same thing applies to `hlines!` and its respective kwargs.

It occurs to me that the most intuitive approach would be `ymax` and `ymin` receiving actual plot coordinates specifying the vertical limits instead of a percentage of the current axis visualization. Or, at least, there should be an option to either choose one or the other, say `coords = :axis` or `coords = :plot` as a kwarg.

**Comment by jkrumbiegel** [comment] 2022-05-12 06:38
These functions are usually used to cover the whole axis, the ymax and ymin options just allow you to tweak that a bit, but we're always thinking about axis-relative positions. If you need data-relative then you can just plot a normal `lines` plot like `lines([x, x], [ymin, ymax])`

**Comment by ffreyer** [comment] 2023-07-26 13:21
I guess this can be closed as "working as intended". The docstring also reflects this.

**Closed by ffreyer** 2023-07-26 13:21 UTC
