### ISSUE TITLE
scatterlines! color does not cycle if different number of data points

### ISSUE THREAD

**Issue by nathanrboyer** [MakieOrg/Makie.jl#3629] opened 2024-02-13 17:21 UTC
- [X] are you running newest version (version from docs) ?  GLMakie v0.9.8
- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)  Same behavior
- [X] What platform + GPU are you on?  Windows 11 with Nvidia GeForce RTX 2060

I would expect each of these lines to have a different color. It used to work that way, and `lines!` does work that way.

```julia
using GLMakie
fig = Figure()
axis = Axis(fig[1,1])
scatterlines!(axis, 0:1, 1:2, label="A")
scatterlines!(axis, 0:0.1:1, 2:0.1:3, label="B")
scatterlines!(axis, 0:1, 3:4, label="C")
Legend(fig[1,2], axis, "Label")
display(fig)
```
![labelerror](https://github.com/MakieOrg/Makie.jl/assets/65452054/d5f68bab-3a5e-4df8-ba25-fdb5ac333bc1)

```julia
using GLMakie
fig = Figure()
axis = Axis(fig[1,1])
lines!(axis, 0:1, 1:2, label="A")
lines!(axis, 0:0.1:1, 2:0.1:3, label="B")
lines!(axis, 0:1, 3:4, label="C")
Legend(fig[1,2], axis, "Label")
display(fig)
```
![labelerror](https://github.com/MakieOrg/Makie.jl/assets/65452054/ad7132e6-60b1-4e88-9db6-bdad1b85fbf7)

**Comment by asinghvi17** [comment] 2024-02-13 17:36
I can't replicate this on master but I can on the latest version as you said @nathanrboyer.

The only thing which touched `scatterlines` since the last release was https://github.com/MakieOrg/Makie.jl/pull/3603, and running that code does indeed solve the issue:

![iTerm2 9qEIOV](https://github.com/MakieOrg/Makie.jl/assets/32143268/0d34d69a-9885-4451-8bb3-9c874b77791c)

You need to run 
```julia
Makie.conversion_trait(::Type{<: ScatterLines}) = PointBased()
```
although I am not entirely sure why this would fix a theming issue.  Maybe because cycling was only enabled for point-based plots?

**Comment by ffreyer** [comment] 2024-08-27 12:33
Closing as fixed/not reproducible

**Closed by ffreyer** 2024-08-27 12:33 UTC
Labels: bug, Makie
