### ISSUE TITLE
xtick is missing for missing data 

### ISSUE THREAD

**Issue by andferrari** [MakieOrg/Makie.jl#3946] opened 2024-06-07 08:40 UTC
- [X] are you running newest version (version from docs) ? CairoMakie v0.12.2
- [X] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?  macbook M1

When plotting with a `missing` at the end (or start) the xtick is missing.

```julia
scatterlines(1:4, [2, 3, missing, 1])
```
<img src="https://github.com/MakieOrg/Makie.jl/assets/8927904/a44027fa-cfcf-4d0a-8419-9e97c48ca255" width="400">

```julia
scatterlines(1:4, [2, 3, 1, missing])
```
<img src="https://github.com/MakieOrg/Makie.jl/assets/8927904/3ba77dc4-bbc3-407c-9088-8bf55e6ddac6" width="400">

**Comment by andferrari** [comment] 2024-06-07 08:52
Thank you for the answer. I was expecting to have the x limit to 4.0 in order to have the same xlims in both case.

**Comment by jkrumbiegel** [comment] 2024-06-07 09:51
I'm not sure if it makes sense to incorporate partial coordinates in the limit calculations, because at least in the case of non-separable transform functions, the final point is undefined in all coordinates. For linearly separable transforms, the partial coordinates would stay known.

**Comment by andferrari** [comment] 2024-06-07 12:04
I'm sorry, I don't really understand these technical problems. What bothers me in the second plot is that it does not reflects the data: we can't see from the plot that we have a missing data

**Comment by ffreyer** [comment] 2024-08-28 13:34
The problem is that you can, for example `rotate!(plot, angle)` which mixes x and y values making the last point undefined.

Closing this as not-planned.

**Closed** 2024-08-28 13:43 UTC
Labels: bug, transformation, Axis
