### ISSUE TITLE
DateTime support for vlines(hlines)

### ISSUE THREAD

**Issue by kosukesando** [MakieOrg/Makie.jl#4119] opened 2024-08-12 09:29 UTC
Attempting to call `vlines(d::DateTime)` results in `MethodError: Cannot convert an object of type Dates.DateTime to an object of type Float64`.

- Makie v0.21.2

**Comment by ffreyer** [comment] 2024-08-28 18:55
Closing as duplicate of #4069

**Closed by ffreyer** 2024-08-28 18:55 UTC
Labels: bug
