### ISSUE TITLE
VSCode displays figure with wrong viewbox after save

### ISSUE THREAD

**Issue by ValentinKaisermayer** [MakieOrg/Makie.jl#2444] opened 2022-11-25 19:40 UTC
```julia
using CairoMakie

fig = Figure()
ax = Axis(fig[1,1])
lines!(cumsum(randn(1000)))
save("img.pdf", fig)
fig
```

![bug](https://user-images.githubusercontent.com/50108075/204048568-82de8054-5ba8-48ee-81c7-1f985157a72c.PNG)

Without the `save("img.pdf", fig)` it works fine. PNG works, SVG not.

**Comment by SimonDanisch** [comment] 2022-11-25 20:00
Duplicate of  https://github.com/MakieOrg/Makie.jl/issues/2438, fixed in https://github.com/MakieOrg/Makie.jl/pull/2440

**Closed by SimonDanisch** 2022-11-25 20:00 UTC
