### ISSUE TITLE
GLMakie Compilation Error: AssertionError: status == GL_FRAMEBUFFER_COMPLETE 

### ISSUE THREAD

**Issue by OmarAshkar** [MakieOrg/Makie.jl#3010] opened 2023-06-15 21:23 UTC
Hi,

I had previous issue and I had to update my OpenGL using the following variable:

```
export MESA_GL_VERSION_OVERRIDE=4.6
```

Now I am getting the following error when I run `using GLMakie`:

```
ERROR: LoadError: AssertionError: status == GL_FRAMEBUFFER_COMPLETE
```

Any help is appreciated.

Thank you!

**Comment by ffreyer** [comment] 2023-06-16 14:34
We should update that assert to show what the status actually is...

This should be a relatively minimal example for setting up a framebuffer and showing its status. Maybe that reproduces the error
```julia
using GLFW
using ModernGL

begin
    window = GLFW.Window()

    # Avoid the OS complaining about non-responsive window
    @async let
        while !GLFW.WindowShouldClose(window)
            GLFW.PollEvents()
            GLFW.SwapBuffers(window)
            sleep(1/30)
        end
        GLFW.DestroyWindow(window)
    end

    # color buffer texture
    cb_id = let
        ref = UInt32[0]
        glGenTextures(1, ref)
        ref[]
    end
    glBindTexture(GL_TEXTURE_2D, cb_id)
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 400, 300, 0, GL_RGBA, GL_UNSIGNED_BYTE, C_NULL)

    # framebuffer
    fb_id = let
        ref = UInt32[0]
        glGenFramebuffers(1, ref)
        ref[]
    end
    glBindFramebuffer(GL_FRAMEBUFFER, fb_id)
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, cb_id, 0)

    statuses = Dict(
        GL_FRAMEBUFFER_COMPLETE => "GL_FRAMEBUFFER_COMPLETE",
        GL_FRAMEBUFFER_UNDEFINED => "GL_FRAMEBUFFER_UNDEFINED",
        GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT => "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
        GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT => "GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
        GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER => "GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",
        GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER => "GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER",
        GL_FRAMEBUFFER_UNSUPPORTED => "GL_FRAMEBUFFER_UNSUPPORTED",
        GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE => "GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
        GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS => "GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS"
    )

    @info statuses[glCheckFramebufferStatus(GL_FRAMEBUFFER)]
end
```

**Comment by ffreyer** [comment] 2023-06-17 15:24
This should be a more complete setup, including all the buffers but not filtering parameters and no texture uploading:

```julia
using GLFW
using ModernGL

begin
    statuses = Dict(
        GL_FRAMEBUFFER_COMPLETE => "GL_FRAMEBUFFER_COMPLETE",
        GL_FRAMEBUFFER_UNDEFINED => "GL_FRAMEBUFFER_UNDEFINED",
        GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT => "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
        GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT => "GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
        GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER => "GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",
        GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER => "GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER",
        GL_FRAMEBUFFER_UNSUPPORTED => "GL_FRAMEBUFFER_UNSUPPORTED",
        GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE => "GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
        GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS => "GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS"
    )

    function gen_buffer(internalformat, format, numbertype, counter)
        ptr = UInt32[0]
        glGenTextures(1, ptr)
        glBindTexture(GL_TEXTURE_2D, ptr[])
        glTexImage2D(GL_TEXTURE_2D, 0, internalformat, 10, 10, 0, format, numbertype, C_NULL)

        if format == GL_DEPTH_STENCIL
            glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, ptr[], 0)
            println(statuses[glCheckFramebufferStatus(GL_FRAMEBUFFER)])
            glFramebufferTexture2D(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_TEXTURE_2D, ptr[], 0)
        else
            glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0 + counter, GL_TEXTURE_2D, ptr[], 0)
            counter += 1
        end
        println(statuses[glCheckFramebufferStatus(GL_FRAMEBUFFER)])

        return counter
    end

    window = GLFW.Window()

    # Avoid the OS complaining about non-responsive window
    task = @async let
        while !GLFW.WindowShouldClose(window)
            GLFW.PollEvents()
            GLFW.SwapBuffers(window)
            sleep(1/30)
        end
        GLFW.DestroyWindow(window)
    end

    fb_id = let
        ref = UInt32[0]
        glGenFramebuffers(1, ref)
        ref[]
    end
    glBindFramebuffer(GL_FRAMEBUFFER, fb_id)

    # color buffer texture
    counter = gen_buffer(GL_RGBA8, GL_RGBA, GL_UNSIGNED_BYTE, 0)

    # object id
    counter = gen_buffer(GL_RG32UI, GL_RG_INTEGER, GL_UNSIGNED_INT, counter)

    # depth-stencil buffer
    counter = gen_buffer(GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, counter)

    # transparency
    counter = gen_buffer(GL_RGBA16F, GL_RGBA, GL_HALF_FLOAT, counter)
    counter = gen_buffer(GL_R8, GL_RED, GL_UNSIGNED_BYTE, counter)

    nothing
end
```

**Comment by ffreyer** [comment] 2023-06-17 21:03
For me these all complete fine. `glGetError()` should give you another error code that might be helpful if you run it after the incomplete attachment messages. It'll give you a number that should be one of the outputs listed here: https://docs.gl/gl4/glGetError (You can make another lookup table like I did for the framebuffer attachments)

**Comment by ffreyer** [comment] 2023-06-18 00:59
That would be GL_INVALID_VALUE. You can check by just calling that.
`glFramebufferTexture2D` doesn't have any fitting reasons listed as far as I can tell, but `glTexImage2D` lists that an unsupported internalformat can trigger this. It also lists that GL_HALF_FLOAT is a 3.0+ feature, so I'm wondering if maybe you're still on an old Version. (See https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml)

**Comment by ffreyer** [comment] 2023-06-25 11:36
No, it relies on WebGL which is different from OpenGL. WGLMakie also has its own rendering code which doesn't include the Float16 buffer

**Comment by ffreyer** [comment] 2024-08-26 11:44
Closing this since this hasn't progressed for a year.

I think my conclusion was that the Float16 buffer fails and that that should be guaranteed to work in OpenGL 3.0+. So either the OpenGL version is not sufficient for Makie or the driver is faulty.

**Closed by ffreyer** 2024-08-26 11:44 UTC
Labels: GLMakie
