### ISSUE TITLE
GLMakie ignores keyboard layout?

### ISSUE THREAD

**Issue by gapato** [MakieOrg/Makie.jl#3496] opened 2023-12-20 12:42 UTC
I have seen #2586 but I suspect the issue to be more general.

- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] Fedora 39, julia v1.9.4 (from julialang.org), GLMakie v0.9.3, NVIDIA GeForce RTX 2060

Here is a small script which displays a window and logs the keys typed. The output should depend on the keyboard layout but it does not. Try with a french/AZERTY layout for example.

```
using GLMakie

function main()
    fig = Figure()
    ax = Axis(fig[1, 1])
    t = range(-1, 1, length=100)
    lines!(ax, t, sinpi.(t))

    on(events(fig.scene).keyboardbutton) do event
        if event.action == Keyboard.press
            println(event.key)
        end
    end

    display(fig)
end

main()
```

EDIT: Could [glfwGetKeyName](https://www.glfw.org/docs/latest/input_guide.html#input_key_name) be part of the solution? It does not appear anywhere in the code at the moment.

**Comment by ffreyer** [comment] 2024-08-26 20:34
Closing as duplicate of #2586

**Closed by ffreyer** 2024-08-26 20:34 UTC
Labels: bug, GLMakie
