### ISSUE TITLE
Why is GLMakie ScreenID only `UInt8`?

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Makie.jl#2388] opened 2022-10-31 20:04 UTC
https://github.com/MakieOrg/Makie.jl/blob/e0cb40096896c3f43a390cd0523138ad644e41fc/GLMakie/src/screen.jl#L1-L4

For some reason I am going above 256 screens and breaking `UInt8`! I'm not sure what exactly defines a screen, but I'm making an interface with some large nested grids of widgets and I hit this error during `display` (maybe I'm designing things badly to hit this, IDK):

```julia
ERROR: InexactError: trunc(UInt8, 256)
Stacktrace:
  [1] throw_inexacterror(f::Symbol, #unused#::Type{UInt8}, val::Int64)
    @ Core ./boot.jl:614
  [2] checked_trunc_uint
    @ ./boot.jl:644 [inlined]
  [3] toUInt8
    @ ./boot.jl:706 [inlined]
  [4] UInt8
    @ ./boot.jl:766 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] cvt1
    @ ./essentials.jl:338 [inlined]
  [7] ntuple
    @ ./ntuple.jl:49 [inlined]
  [8] convert
    @ ./essentials.jl:339 [inlined]
  [9] push!
    @ ./array.jl:1057 [inlined]
 [10] #43
    @ ~/.julia/packages/GLMakie/Q73P7/src/screen.jl:302 [inlined]
 [11] get!(default::GLMakie.var"#43#45"{GLMakie.Screen{GLFW.Window}, Scene}, h::Dict{We
akRef, UInt8}, key::WeakRef)
    @ Base ./dict.jl:481
 [12] insertplots!(screen::GLMakie.Screen{GLFW.Window}, scene::Scene)
    @ GLMakie ~/.julia/packages/GLMakie/Q73P7/src/screen.jl:300
 [13] (::GLMakie.var"#44#46"{GLMakie.Screen{GLFW.Window}})(s::Scene)
    @ GLMakie ~/.julia/packages/GLMakie/Q73P7/src/screen.jl:308
 [14] foreach(f::GLMakie.var"#44#46"{GLMakie.Screen{GLFW.Window}}, itr::Vector{Scene})
    @ Base ./abstractarray.jl:2774
 [15] insertplots!(screen::GLMakie.Screen{GLFW.Window}, scene::Scene)
    @ GLMakie ~/.julia/packages/GLMakie/Q73P7/src/screen.jl:308
 [16] display(screen::GLMakie.Screen{GLFW.Window}, scene::Scene; connect::Bool)
    @ GLMakie ~/.julia/packages/GLMakie/Q73P7/src/display.jl:12
 [17] display
    @ ~/.julia/packages/GLMakie/Q73P7/src/display.jl:1 [inlined]
 [18] #display#990
    @ ~/.julia/packages/Makie/fyg5R/src/display.jl:133 [inlined]
 [19] display(screen::GLMakie.Screen{GLFW.Window}, figlike::Figure)
    @ Makie ~/.julia/packages/Makie/fyg5R/src/display.jl:130
 [20] display(figlike::Figure; backend::Module, screen_config::Base.Pairs{Symbol, Union
{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/fyg5R/src/display.jl:123
 [21] display
    @ ~/.julia/packages/Makie/fyg5R/src/display.jl:109 [inlined]
 [22] selectcolors(raw_map::Matrix{RGB{Float64}}; ncategories::Int64, match::Vector{Any
}, points::Vector{Vector{Point{2, Float32}}}, polygons::Vector{Vector{Vector{Point{2, F
```

This is hit here, where `screen.screens` is a `Vector{ScreenArea}`, defined above.
https://github.com/MakieOrg/Makie.jl/blob/e0cb40096896c3f43a390cd0523138ad644e41fc/GLMakie/src/screen.jl#L300-L304

**Comment by jkrumbiegel** [comment] 2022-10-31 20:41
Every `Block` like `Axis`, `Label`, `Box`, `Slider`, etc. has one container scene that it plots its own plot objects into. `Axis` and `Axis3` even have another one, for the actual plotting canvas. So depending on how many of those objects you use, you might reach the limit earlier than expected. And the value is a UInt8 because it's stored in some OpenGL buffer that just has 8 bits per pixel, I'm not sure about the details right now but it's not trivial to change.

**Comment by rafaqz** [comment] 2022-10-31 21:14
Ok. I have a 5 × n widget grid where n might get to 40 or so. So that combined with plots and other things in the interface will hit 256.

I guess I can limit the application at 30 lines if input, I was kind if overdoing it anyway. 

But I imagine other people will hit this too as they start building more complicated interfaces

**Comment by jkrumbiegel** [comment] 2022-10-31 21:23
Yes I agree it would be better if there was a higher limit, attempting to change it goes above my current expertise with the GLMakie backend though.

**Comment by Moelf** [comment] 2022-10-31 21:36
duplicate of https://github.com/MakieOrg/Makie.jl/issues/665 ?

**Comment by SimonDanisch** [comment] 2022-10-31 21:52
Yup :(

**Closed by SimonDanisch** 2022-10-31 21:52 UTC
