### ISSUE TITLE
legend scheme for `stemplot` doesn't use `stemcolor` when transparency is provided?

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/Makie.jl#2506] opened 2022-12-18 01:59 UTC
`stemcolor` is used to draw the line in the legend representing the data series for a `stemplot`. however, not when `stemcolor` has a transparency... feel like it should draw the transparent line, no? for my purposes of visualizing a probability mass function, at least, seems always using `stemcolor` is better, even if transparent.

`CairoMakie` v0.10.0.

```
function my_stem_plot(legend_makes_sense::Bool)
	xs = 1:10
	
	fig = Figure()
	ax  = Axis(fig[1, 1])
	stem!(xs, 100 .- xs .^ 2,
		trunkcolor="black", 
		stemcolor=legend_makes_sense ? "red" : ("red", 0.2),
		color="red",
		label="pmf"
	)
	axislegend()
	fig
end
```
(inconsistent) results (look at legend):
<img width="383" alt="Screen Shot 2022-12-17 at 5 58 38 PM" src="https://user-images.githubusercontent.com/30643894/208276081-b8eed6f7-e275-4e05-84cb-fe5c501b14e6.png">

**Comment by jkrumbiegel** [comment] 2022-12-21 10:10
It does adjust the alpha of the legend marker line, this makes the black line below it visible. There are two lines because the legend marker is created automatically by stacking those for the scatter and the two line plots that make up the stem plot. To fix this, we could create a specific marker for stem plots that arranges these elements differently. For example, a trunk line at the bottom and a stem going off vertically with a scatter on top, mirroring the actual plot structure.

**Comment by SimonEnsemble** [comment] 2022-12-22 02:09
> create a specific marker for stem plots that arranges these elements differently. For example, a trunk line at the bottom and a stem going off vertically with a scatter on top, mirroring the actual plot structure.

this is a cool idea!
or, at least, just incl. the stems and not the trunk. in my mind, the stem only serves to show the y=0 baseline, kind of like a secondary x-axis 😄 

I can get around this currently by drawing the trunk manually in a separate line without a `label` passed to it. thx!

**Comment by jkrumbiegel** [comment] 2022-12-27 15:56
I'll close this as the described "bug" is not a bug, and if we want to create a better scheme we should make that a separate issue.

**Closed by jkrumbiegel** 2022-12-27 15:56 UTC
