### ISSUE TITLE
`window_open` `Observable`s not notified

### ISSUE THREAD

**Issue by lmshk** [MakieOrg/Makie.jl#2414] opened 2022-11-10 14:28 UTC
I am creating a GLMakie window from a script and want to block that script until the window is closed (because otherwise the process exits). For this purpose, I attach a listener to the `Figure`'s **`window_open`** `Observable` that notifies s a `Base.Event` when the value becomes `false`. This worked correctly before, but the **listener stopped being called** starting with Makie **v0.18.0**.

A simplified example looks like this:

    using GLMakie
    closed = Base.Event()
    f = Figure()
    display(f)
    on(events(f).window_open) do is_open
        !is_open && notify(closed)
    end
    wait(closed)

When running this and manually closing the window, the script will remain blocked.

(I suspected that this is somehow related to #2306 but didn't confirm that because I couldn't figure out how to `]add` both `Makie` and `GLMakie` at the specific commits and without error.)

After looking around a little, I noticed that there are multiple `Events` instances related to my plot, all of which have a `window_open` `Observable`, but I am confused about which of these I should use:

    screen = begin
        f = Figure()
        display(f)
    end

    on(events(f).window_open) do _; @info "events(f)" end
    on(screen.window_open) do _; @info "screen" end
    on(events(f.scene).window_open) do _; @info "events(f.scene)" end

On Makie v0.17, when closing the window, the preceding code prints

    [ Info: events(f.scene)
    [ Info: events(f)
    [ Info: events(f.scene)
    [ Info: screen

while on v0.18 this prints just

    [ Info: events(f.scene)

It seems like I can just use the `scene` events as a workaround, but the fact that this is triggered twice on v0.17 makes me think that I am doing something wrong. Am I meant to use it this way, or is there another `Events` instance I missed, or is this a bug?

**Comment by SimonDanisch** [comment] 2022-11-10 14:33
Seems like a regression, I'll take a look...Meanwhile, you have `wait(screen)` for this...
so e.g.:
```julia
screen = display(fig)
wait(screen)
```

**Comment by SimonDanisch** [comment] 2022-11-10 14:34
And if you use `.window_open` you should use the one from `scene.events`, since `screen.window_open` only exist as part of a work around...

**Comment by SimonDanisch** [comment] 2022-11-10 14:59
Can you explain, maybe with a very easy & short code example, why wait is not working in your case? I can't see the reason from the linked post...

**Comment by lmshk** [comment] 2022-11-10 15:19
Maybe I'm missing something... in my setup, the `display` call happens from a callback (presumably called from some event loop), while the `wait` needs to happen on the main thread to prevent the process from exiting. So where I want to `wait` I don't have the `Screen`.

I'll paste the linked example here:

```julia
closed = Base.Event()
selection = Observable(...)  # this triggers and controls figure (re)construction

window_open_callback = Ref{Any}(nothing)
on(selection) do selected
    # filter data etc...
    figure = build_figure(data; selection)

    isnothing(window_open_callback[]) || off(window_open_callback[])
    display(figure)  # <- Screen available here
    window_open_callback[] = on(events(figure).window_open) do is_open
        !is_open && notify(closed)
    end
end

notify(selection)
wait(closed)  # <- Screen needed here
```

**Comment by lmshk** [comment] 2022-11-10 15:23
(But my understanding is that doing that same thing on `events(figure.scene).window_open` should work both on v0.17 and v0.18, so this is fine for me.)

**Comment by SimonDanisch** [comment] 2022-11-10 15:46
Can you do: 
```julia
screen = GLMakie.Screen()
on(selection) do selected
    # filter data etc...
    figure = build_figure(data; selection)
    display(screen, figure)  # <- Screen available here
end
wait(screen)
```
?

**Comment by lmshk** [comment] 2022-11-10 16:02
That works perfectly, thanks very much!

---

Regarding the original post, I just realized that the situation is more complex than I noticed at first. On v0.18:

```
f = Figure()
display(f)
on(f.scene.events.window_open) do is_open; @info "XXX" is_open end
on(f.scene.events.window_open) do is_open; @info "YYY" is_open end
```

Now:

- closing the window triggers only the "YYY" callback
- re`display(f)` triggers both callbacks
- closing the window again triggers only the "YYY" callback

**Comment by lmshk** [comment] 2022-11-24 22:44
> Can you do:
> 
> ```julia
> screen = GLMakie.Screen()
> on(selection) do selected
>     # filter data etc...
>     figure = build_figure(data; selection)
>     display(screen, figure)  # <- Screen available here
> end
> wait(screen)
> ```
> 
> ?

This worked correctly with v0.18.2, but stopped working with v0.18.3: Calling `display` the second time (with the first rebuilt figure) leaves the old figure on screen (now displaying both, overlapping), but resizing the window only resizes the newer figure. Calling `empty!(screen)` now closes the window. How should I replace the displayed figure without closing the window? (Should this be a separate issue?)

**Comment by SimonDanisch** [comment] 2022-11-25 22:28
Oops... Pushed a fix for it https://github.com/MakieOrg/Makie.jl/commit/bcfdd194e7e1c0af62dcb02889ad8bd439de99ef
Will tag soon :)

**Comment by ffreyer** [comment] 2022-12-26 12:31
This and #2419 don't work because

https://github.com/MakieOrg/Makie.jl/blob/f124a016d2662ec12d31dac4098b7a92622bd3b1/src/display.jl#L41-L50

removes the first callback from `obs.listeners` during the listener iteration in 

https://github.com/JuliaGizmos/Observables.jl/blob/27b3fc61fed83a104cdc7b79a35f25f111558e02/src/Observables.jl#L168-L174

so it jumps to the third instead of second.

**Closed** 2023-01-01 18:40 UTC
