### ISSUE TITLE
lines example not working

### ISSUE THREAD

**Issue by gdkrmr** [MakieOrg/Makie.jl#2705] opened 2023-02-22 16:19 UTC
The following code from the documentation:

```julia
using GLMakie
f = Figure()
Axis(f[1, 1])

xs = 0:0.01:10
ys = 0.5 .* sin.(xs)

lines!(xs, ys)
lines!(xs, ys .- 1, linewidth=5)
lines!(xs, ys .- 2, linewidth=5, color=ys)
lines!(xs, ys .- 3, linestyle=:dash)

f
```
produces this:

![test](https://user-images.githubusercontent.com/12512930/220687803-71f09962-dfa1-42df-a774-737eeba66cd0.png)

I saw it flashing correctly the first time I executed the code above, so I guess it gets rendered correctly at some point.

Tested with GLMakie 0.8.2, Julia {1.8, 1.9} on Manjaro Linux

**Comment by SimonDanisch** [comment] 2023-02-22 16:34
Pretty sure this is a duplicate of https://github.com/MakieOrg/Makie.jl/issues/1460

**Closed by SimonDanisch** 2023-02-22 16:34 UTC
