### ISSUE TITLE
Create line plot with a specific number of markers (like markerindices in matlab)

### ISSUE THREAD

**Issue by draftman9** [MakieOrg/Makie.jl#3963] opened 2024-06-15 06:25 UTC
### Feature description

I want to create line plot with markers. However I found the markers are too many, so I want to control the number/density of the markers. I found a general method to satisfy my demand though, label can not be displayed correctly.

Here is the featured function analogue reference:

https://www.mathworks.com/help/matlab/creating_plots/create-line-plot-with-markers.html#bvcbmlx-1:~:text=1%20.6%20.6%5D)-,Control%20Placement%20of%20Markers%20Along%20Line,-Try%20This%20Example

**Comment by ffreyer** [comment] 2024-08-28 13:53
Closing as duplicate of #2563

**Closed by ffreyer** 2024-08-28 13:53 UTC
Labels: enhancement
