### ISSUE TITLE
Polar Histogram

### ISSUE THREAD

**Issue by toihr** [MakieOrg/Makie.jl#4279] opened 2024-08-28 15:34 UTC
### Feature description
A way to make Polar Histograms, which could be used to make windroses or similar.

### For plot types, please add an image of how it should look like
![PolarHist](https://github.com/user-attachments/assets/eebbf337-26a7-4a1e-bf17-678552bb3aac)

**Comment by asinghvi17** [comment] 2024-08-28 17:40
For reference, this is the current state of things:
```julia
using CairoMakie
hist(rand(100) .* π; axis = (; type= PolarAxis))
```
![iTerm2 u6dySy](https://github.com/user-attachments/assets/b5e898bf-a403-4092-9156-d2df69e14945)

**Comment by asinghvi17** [comment] 2024-08-28 18:17
Ah, looks like the error is here:

https://github.com/MakieOrg/Makie.jl/blob/223e64c3607b00ffc8bdf73f62c04664f7608af5/CairoMakie/src/utils.jl#L113-L118

This should probably check the `transform_func` and return a `GeometryBasics.Polygon` or something...

**Comment by ffreyer** [comment] 2024-08-28 18:42
Closing as duplicate of #3175

**Closed by ffreyer** 2024-08-28 18:42 UTC
Labels: enhancement, CairoMakie, PolarAxis
