### ISSUE TITLE
Shading goes black for meshes featuring locally inverted normals

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MakieOrg/Makie.jl#3755] opened 2024-04-01 09:05 UTC
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? -> `Ubuntu 22.04`, `NVIDIA T550 Laptop GPU`

It looks like there is an interpolation error for color data (and/or shading?) when the normal directions are inverted. This is probably due to normal direction interpolation which will return a zero length vector when interpolating between two adjacent and inverted normal vectors. 

Here I inverted the face orientations for half of a sphere. The only thing to see here is that the shading seems to flip to a different state. This looks like the desired behaviour: 
![Screenshot from 2024-04-01 09-51-28](https://github.com/MakieOrg/Makie.jl/assets/8392709/f0ccbc9e-69ba-489a-80da-97185bfd6c5e)

However, when the normal directions are exactly negated it looks like we get funny behaviour. Here I inverted the faces halfway a quadrilateral plate mesh. As you can see we now get sudden and odd back regions: 
![Screenshot from 2024-04-01 09-54-50](https://github.com/MakieOrg/Makie.jl/assets/8392709/10f3bf13-253f-4e20-9ec4-81800a3e72e5)

It looks like perhaps Makie should detect that the interpolation produced a zero length vector, next it should be renormalised and be forced to point in the direction of the closest healthy vertex or face normal. 

Below is some code I used to study this, which features simple sets of triangles which produces the following image: 
![image](https://github.com/MakieOrg/Makie.jl/assets/8392709/b0162bed-f1b4-45c9-afd2-ed719f8cbe62)

```
using GLMakie
using GeometryBasics

F1 = TriangleFace{Int64}[[1,2,3],[6,4,5]]
V1 = Point3{Float64}[[0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [2.25, 1.0, 0.0], [2.25, -1.0, 0.0],[1.25,0,0]]
C1 = [v[1] for v ∈ V1] # x-coordinates as colors

F2 = TriangleFace{Int64}[[1,2,3],[3,4,5]]
V2 = Point3{Float64}[[0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [2.0, 1.0, 0.0], [2.0, -1.0, 0.0]]
C2 = [v[1] for v ∈ V2] # x-coordinates as colors

F3 = TriangleFace{Int64}[[1,2,3],[5,4,3]]
V3 = Point3{Float64}[[0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [2.0, 1.0, 0.0], [2.0, -1.0, 0.0]]
C3 = [v[1] for v ∈ V3] # x-coordinates as colors

F4 = TriangleFace{Int64}[[1,2,3],[4,5,6]]
V4 = Point3{Float64}[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0], [1.25, 0.0, 0.0], [1.25, 1.0, 0.0],[2.25, 0.0, 0.0]]
C4 = [v[1] for v ∈ V4] # x-coordinates as colors

F5 = TriangleFace{Int64}[[1,2,3],[3,4,2]]
V5 = Point3{Float64}[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0], [2.0, 0.0, 0.0]]
C5 = [v[1] for v ∈ V5] # x-coordinates as colors

F6 = TriangleFace{Int64}[[1,2,3],[2,4,3]]
V6 = Point3{Float64}[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 1.0, 0.0], [2.0, 0.0, 0.0]]
C6 = [v[1] for v ∈ V6] # x-coordinates as colors


## Visualization
fig = Figure(size=(800,800))

ax = Axis3(fig[1, 1], aspect = :data, xlabel = "X", ylabel = "Y", zlabel = "Z", title = "Separate, inverted")
hp = poly!(ax,GeometryBasics.Mesh(V1,F1), color=C1, shading = FastShading, transparency=false,colormap=Reverse(:Spectral),strokewidth=3,strokecolor=:black)

ax = Axis3(fig[1, 2], aspect = :data, xlabel = "X", ylabel = "Y", zlabel = "Z", title = "Touching, inverted")
hp = poly!(ax,GeometryBasics.Mesh(V2,F2), color=C2, shading = FastShading, transparency=false,colormap=Reverse(:Spectral),strokewidth=3,strokecolor=:black)

ax = Axis3(fig[1, 3], aspect = :data, xlabel = "X", ylabel = "Y", zlabel = "Z", title = "Touching consistent")
hp = poly!(ax,GeometryBasics.Mesh(V3,F3), color=C3, shading = FastShading, transparency=false,colormap=Reverse(:Spectral),strokewidth=3,strokecolor=:black)

ax = Axis3(fig[2, 1], aspect = :data, xlabel = "X", ylabel = "Y", zlabel = "Z", title = "Separate,inverted")
hp = poly!(ax,GeometryBasics.Mesh(V4,F4), color=C4, shading = FastShading, transparency=false,colormap=Reverse(:Spectral),strokewidth=3,strokecolor=:black)

ax = Axis3(fig[2, 2], aspect = :data, xlabel = "X", ylabel = "Y", zlabel = "Z", title = "Touching, inverted")
hp = poly!(ax,GeometryBasics.Mesh(V5,F5), color=C5, shading = FastShading, transparency=false,colormap=Reverse(:Spectral),strokewidth=3,strokecolor=:black)

ax = Axis3(fig[2, 3], aspect = :data, xlabel = "X", ylabel = "Y", zlabel = "Z", title = "Touching consistent")
hp = poly!(ax,GeometryBasics.Mesh(V6,F6), color=C6, shading = FastShading, transparency=false,colormap=Reverse(:Spectral),strokewidth=3,strokecolor=:black)

fig
```

**Comment by ffreyer** [comment] 2024-04-02 11:42
We could try doing something like `normal = normalize(normal + vec3(1e-6, 0, 0))` at the start of
https://github.com/MakieOrg/Makie.jl/blob/46e14a829340d1cca677991de4a23da36fcbc610/GLMakie/assets/shader/lighting.frag#L40-L59
to avoid interpolating to vec3(0). This probably requires earlier `normalize(normal)` calls to be removed, e.g.
https://github.com/MakieOrg/Makie.jl/blob/46e14a829340d1cca677991de4a23da36fcbc610/GLMakie/assets/shader/mesh.frag#L115
since this may lead to nan on some gpus. CairoMakie (primitves.jl) and WGLMakie (shaders in assets folder) should be pretty analogous.

**Comment by ffreyer** [comment] 2024-08-27 19:54
Closing as duplicate of #3755

**Closed by ffreyer** 2024-08-27 19:54 UTC
Labels: bug, good first issue
