### ISSUE TITLE
mouse position or `to_world` wrong in subscene

### ISSUE THREAD

**Issue by goretkin** [MakieOrg/Makie.jl#457] opened 2020-04-01 03:33 UTC
```julia
import GLMakie

import GLMakie: AbstractPlotting
import .AbstractPlotting: lift, Point2f0
import .AbstractPlotting: Scene

import MakieLayout
import MakieLayout: LAxis, GridLayout

scene, layout = let nrows=1, ncols=1
  scene = Scene(; camera = AbstractPlotting.campixel!,
    resolution = (800, 800),
    backgroundcolor = :white)
  gl = GridLayout(scene, nrows, ncols, alignmode = MakieLayout.Outside(30))
  scene, gl
end

# layout[1,1] = p_workspace = LAxis(scene, title="planning workspace")
layout[1,1] = laxis = LAxis(scene, title="workspace")


mousemarker = lift(laxis.scene.events.mouseposition) do mp
  r = [Point2f0(AbstractPlotting.to_world(laxis.scene, Point2f0(mp)))]
  @show r
  return r
end

AbstractPlotting.scatter!(laxis, mousemarker; markersize=3)
display(scene)
```

The scatter point has a consistent offset from the cursor. The offset is in screen units, since zooming the plot does not change the offset.

**Comment by asinghvi17** [comment] 2020-04-01 03:49
A simple `vbox` also displays this offset behaviour.  I suspect it is because the reported mouseposition is not relative to the Scene's origin, but to the Screen.

**Comment by brechetp** [comment] 2020-12-01 15:55
It seems it could be fixed by overloading to_world(axis::LAxis, point::T) ?

```julia
using AbstractPlotting
using AbstractPlotting: StaticVector
import AbstractPlotting: to_world

function AbstractPlotting.to_world(axis::LAxis, point::T) where T <: StaticVector
    cam = axis.scene.camera
    x = to_world(
        point,
        inv(AbstractPlotting.transformationmatrix(ax1.scene)[]) *
        inv(cam.view[]) *
        inv(cam.projection[]),
        T(widths(pixelarea(axis)[]))
    )
    Point2f0(x[1], x[2])
end
```

(taking the pixelarea of the axis view and not of the scene).

I am new to Julia and don't know much about view projections, so I have no idea if / why this fix could be the correct one. Besides, if even so, I don't know where to fix it, since LAxis is exported by MakieLayout (so probably add the function in MakieLayout, but not sure where).

**Comment by goretkin** [comment] 2021-11-15 15:53
Here is the same code, updated:
```julia
using GLMakie
using Makie

f = Figure()

ax = Axis(f[1, 1], title = "Demo")

mousemarker = lift(events(f).mouseposition) do mp
    r = [Point2f0(Makie.to_world(ax.scene, Point2f0(mp)))]
    @show r
    return r
  end

scatter!(ax, mousemarker; markersize=3)
display(f)
```



The documentation currently does say
> events.mouseposition which holds the current cursor position relative to the window as NTuple{2, Float64} in pixel
which happens regardless of whether you look at `events(ax.scene).mouseposition` or `events(f).mouseposition`.

So what's the right way to do this?

**Comment by goretkin** [comment] 2021-11-15 15:56
Here is one way:

```julia
using GLMakie
using Makie

fig = Figure()
ax = Axis(fig[1, 1], title = "Demo")

mousemarker = lift(events(fig).mouseposition) do mp
    # `mp` is relative to the window, throw it away.
    r = [mouseposition(ax.scene)]
    @show r
    return r
  end

scatter!(ax, mousemarker; markersize=15)
display(fig)
```

**Comment by ffreyer** [comment] 2024-08-21 18:59
This is working as intended.
`events(...).mouseposition` is the raw pixel-space mouse position, relative to the origin of the window. The events struct is shared across all scenes, so this is the same for all. 
`mouseposition_px(...)` is the pixel space mouse position with scene offsets applied.
`mouseposition(...)` is the world space mouse position, which also takes scene offsets into account on the way. This may change if we decide to merge #4090.

I'll close this since there isn't a bug here.

**Closed by ffreyer** 2024-08-21 18:59 UTC
Labels: bug
