### ISSUE TITLE
Arrows extend too far

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [MakieOrg/Makie.jl#3255] opened 2023-09-26 13:58 UTC
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?

The `arrows` function draws an arrow tail and an arrow head. However, the tail extends the whole vector length, and the head then sits on top of that, which adds further length to the arrow. 

Currently the default behaviour seems to create these "arrows that are too long", for instance in the below I plot a unit vector in the x-direction. The result is a vector longer than 1.  

```julia
using Makie

p = [Point3f(0.0,0.0,0.0)]
u = [Point3f(1.0,0.0,0.0)]

# Visualize 
fig1 = Figure(resolution = (1200, 800))
ax = Axis3(fig1[1, 1], aspect = :data)

arrows!(p,u,arrowcolor = :yellow, linecolor = :blue,align = :origin)

fig1
```

![Screenshot from 2023-09-26 14-29-58](https://github.com/MakieOrg/Makie.jl/assets/8392709/a8075e62-d9b2-4d03-a001-457c79e38fe5)

It would be great if this was fixed and that the default behaviour produces arrows of the correct total length, in other words like this: 

![Screenshot from 2023-09-26 14-29-58_v2](https://github.com/MakieOrg/Makie.jl/assets/8392709/e88c3948-72a7-406e-a1eb-9405711d3159)

I think the above should be the default, but you may also consider adding the fix as an option e.g. lengthdefinition=:tail (current default),  lengthdefinition=:full (what I want).

**Comment by ffreyer** [comment] 2023-09-26 15:17
Duplicate of #2472, #1206

**Comment by Kevin-Mattheus-Moerman** [comment] 2023-09-26 15:45
@ffreyer thanks, apologies I should have looked those up.

**Comment by ffreyer** [comment] 2024-08-26 14:33
Closing as duplicate

**Closed by ffreyer** 2024-08-26 14:33 UTC
Labels: bug, arrows
