### ISSUE TITLE
Failing tests on Ubuntu 20.04 (using i3wm) and Julia 1.6.3 (GLMakie)

### ISSUE THREAD

**Issue by ajaust** [MakieOrg/Makie.jl#1443] opened 2021-11-12 09:06 UTC
Thanks for creating this interesting plotting library. I wanted to try out Makie on my machine. I just got a completely fresh installation of Julia and afterwards followed the steps from the README.md

```
julia>]
pkg> add GLMakie
pkg> test GLMakie
```

to set up Makie. However, I got failing tests. Running the tests a second time still gives the same results with the only difference that all extra packages/dependencies are already available locally.

Let me know if you need any more input, like glxinfo or similar, or help with this.

## Expectations and Observations

I expected the tests to pass, but I got 5 out of 9 tests failing.

```
Test Summary:                                             | Pass  Fail  Total
unit tests                                                |    4     5      9
  Window handling                                         |    1     5      6
  Pick a plot element or plot elements inside a rectangle |    3            3
ERROR: LoadError: LoadError: Some tests did not pass: 4 passed, 5 failed, 0 errored, 0 broken.
```

## System information

- Ubuntu 20.04 using i3 as window manager
- Julia Version 1.6.3 (2021-09-23), fresh installation using the binaries from Julia homepage

## Error message

Error message from second test run, i.e., the dependencies are already installed.

```
(@v1.6) pkg> test GLMakie
     Testing GLMakie
      Status `/tmp/jl_hhDiTk/Project.toml`
  [5789e2e9] FileIO v1.11.2
  [e9467ef8] GLMakie v0.4.7
  [5c1252a2] GeometryBasics v0.4.1
  [6218d12a] ImageMagick v1.2.2
  [ee78f7c6] Makie v0.15.3
  [44cfe95a] Pkg `@stdlib/Pkg`
  [8dfed614] Test `@stdlib/Test`
      Status `/tmp/jl_hhDiTk/Manifest.toml`
  [621f4979] AbstractFFTs v1.0.1
  [1520ce14] AbstractTrees v0.3.4
  [79e6a3ab] Adapt v3.3.1
  [27a7e980] Animations v0.4.1
  [4fba245c] ArrayInterface v3.1.40
  [67c07d97] Automa v0.8.2
  [13072b0f] AxisAlgorithms v1.0.1
  [fa961155] CEnum v0.4.1
  [d360d2e6] ChainRulesCore v1.11.1
  [9e997f8a] ChangesOfVariables v0.1.1
  [a2cac450] ColorBrewer v0.4.0
  [35d6a980] ColorSchemes v3.15.0
  [3da002f7] ColorTypes v0.11.0
  [c3611d14] ColorVectorSpace v0.9.7
  [5ae59095] Colors v0.12.8
  [34da2185] Compat v3.40.0
  [d38c429a] Contour v0.5.7
  [9a962f9c] DataAPI v1.9.0
  [864edb3b] DataStructures v0.18.10
  [e2d170a0] DataValueInterfaces v1.0.0
  [b429d917] DensityInterface v0.3.3
  [31c24e10] Distributions v0.25.28
  [ffbed154] DocStringExtensions v0.8.6
  [da5c29d0] EllipsisNotation v1.1.1
  [c87230d0] FFMPEG v0.4.1
  [7a1cc6ca] FFTW v1.4.5
  [5789e2e9] FileIO v1.11.2
  [1a297f60] FillArrays v0.12.7
  [53c48c17] FixedPointNumbers v0.8.4
  [59287772] Formatting v0.4.2
  [b38be410] FreeType v4.0.0
  [663a7486] FreeTypeAbstraction v0.9.2
  [f7f18e0c] GLFW v3.4.1
  [e9467ef8] GLMakie v0.4.7
  [5c1252a2] GeometryBasics v0.4.1
  [a2bd30eb] Graphics v1.1.1
  [3955a311] GridLayoutBase v0.6.4
  [42e2da0e] Grisu v1.0.2
  [615f187c] IfElse v0.1.1
  [a09fc81d] ImageCore v0.9.3
  [82e4d734] ImageIO v0.5.9
  [6218d12a] ImageMagick v1.2.2
  [9b13fd28] IndirectArrays v1.0.0
  [d25df0c9] Inflate v0.1.2
  [a98d9a8b] Interpolations v0.13.4
  [8197267c] IntervalSets v0.5.3
  [3587e190] InverseFunctions v0.1.2
  [92d709cd] IrrationalConstants v0.1.1
  [f1662d9f] Isoband v0.1.1
  [c8e1da08] IterTools v1.3.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.3.0
  [682c06a0] JSON v0.21.2
  [5ab0869b] KernelDensity v0.6.3
  [b964fa9f] LaTeXStrings v1.3.0
  [2ab3a3ac] LogExpFunctions v0.3.5
  [ee78f7c6] Makie v0.15.3
  [20f20a25] MakieCore v0.1.3
  [dbb5928d] MappedArrays v0.4.1
  [7eb4fadd] Match v1.1.0
  [0a4f8689] MathTeXEngine v0.2.1
  [7269a6da] MeshIO v0.4.9
  [e1d29d7a] Missings v1.0.2
  [66fc600b] ModernGL v1.1.3
  [e94cdb99] MosaicViews v0.3.3
  [77ba4419] NaNMath v0.3.5
  [f09324ee] Netpbm v1.0.2
  [510215fc] Observables v0.4.0
  [6fe1bfb0] OffsetArrays v1.10.8
  [52e1d378] OpenEXR v0.3.2
  [bac558e1] OrderedCollections v1.4.1
  [90014a1f] PDMats v0.11.3
  [f57f5aa1] PNGFiles v0.3.12
  [19eb6ba3] Packing v0.4.2
  [5432bcbf] PaddedViews v0.5.10
  [69de0a69] Parsers v2.1.2
  [eebad327] PkgVersion v0.1.1
  [995b91a9] PlotUtils v1.0.15
  [647866c9] PolygonOps v0.1.2
  [21216c6a] Preferences v1.2.2
  [92933f4c] ProgressMeter v1.7.1
  [1fd47b50] QuadGK v2.4.2
  [c84ed2f1] Ratios v0.4.2
  [189a3867] Reexport v1.2.2
  [05181044] RelocatableFolders v0.1.3
  [ae029012] Requires v1.1.3
  [79098fc4] Rmath v0.7.0
  [fdea26ae] SIMD v3.3.1
  [7b38b023] ScanByte v0.3.0
  [6c6a2e73] Scratch v1.1.0
  [65257c39] ShaderAbstractions v0.2.8
  [992d4aef] Showoff v1.0.3
  [73760f76] SignedDistanceFields v0.4.0
  [a2af1166] SortingAlgorithms v1.0.1
  [276daf66] SpecialFunctions v1.8.1
  [cae243ae] StackViews v0.1.1
  [aedffcd0] Static v0.4.0
  [90137ffa] StaticArrays v1.2.13
  [82ae8749] StatsAPI v1.0.0
  [2913bbd2] StatsBase v0.33.12
  [4c63d2b9] StatsFuns v0.9.13
  [09ab397b] StructArrays v0.6.3
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.6.0
  [62fd8b95] TensorCore v0.1.1
  [731e570b] TiffImages v0.5.2
  [3bb67fe8] TranscodingStreams v0.9.6
  [1cfade01] UnicodeFun v0.4.1
  [efce3f68] WoodburyMatrices v0.5.5
  [6e34b625] Bzip2_jll v1.0.8+0
  [83423d85] Cairo_jll v1.16.1+0
  [5ae413db] EarCut_jll v2.2.3+0
  [2e619515] Expat_jll v2.2.10+0
  [b22a6f82] FFMPEG_jll v4.4.0+0
  [f5851436] FFTW_jll v3.3.10+0
  [a3f928ae] Fontconfig_jll v2.13.93+0
  [d7e528f0] FreeType2_jll v2.10.4+0
  [559328eb] FriBidi_jll v1.0.10+0
  [0656b61e] GLFW_jll v3.3.5+1
  [78b55507] Gettext_jll v0.21.0+0
  [7746bdde] Glib_jll v2.68.3+0
  [3b182d85] Graphite2_jll v1.3.14+0
  [2e76f6c2] HarfBuzz_jll v2.8.1+0
  [c73af94c] ImageMagick_jll v6.9.10-12+3
  [905a6f67] Imath_jll v3.1.2+0
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+2
  [aacddb02] JpegTurbo_jll v2.1.0+0
  [c1c5ebd0] LAME_jll v3.100.1+0
  [dd4b983a] LZO_jll v2.10.1+0
  [e9f186c6] Libffi_jll v3.2.2+0
  [d4300ac3] Libgcrypt_jll v1.8.7+0
  [7e76a0d4] Libglvnd_jll v1.3.0+3
  [7add5ba3] Libgpg_error_jll v1.42.0+0
  [94ce4f54] Libiconv_jll v1.16.1+1
  [4b2f31a3] Libmount_jll v2.35.0+0
  [89763e89] Libtiff_jll v4.3.0+0
  [38a345b3] Libuuid_jll v2.36.0+0
  [856f044c] MKL_jll v2021.1.1+2
  [e7412a2a] Ogg_jll v1.3.5+0
  [18a262bb] OpenEXR_jll v3.1.1+0
  [458c3c95] OpenSSL_jll v1.1.10+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [91d4177d] Opus_jll v1.3.2+0
  [2f80f16e] PCRE_jll v8.44.0+0
  [30392449] Pixman_jll v0.40.1+0
  [f50d1b31] Rmath_jll v0.3.0+0
  [02c8fc9c] XML2_jll v2.9.12+0
  [aed1982a] XSLT_jll v1.1.34+0
  [4f6342f7] Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] Xorg_libXau_jll v1.0.9+4
  [935fb764] Xorg_libXcursor_jll v1.2.0+4
  [a3789734] Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] Xorg_libXext_jll v1.3.4+4
  [d091e8ba] Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] Xorg_libXi_jll v1.7.10+4
  [d1454406] Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] Xorg_libXrender_jll v0.9.10+4
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] Xorg_libxcb_jll v1.13.0+3
  [c5fb5394] Xorg_xtrans_jll v1.4.0+3
  [3161d3a3] Zstd_jll v1.5.0+0
  [9a68df92] isoband_jll v0.2.2+0
  [0ac62f75] libass_jll v0.15.1+0
  [f638f0a6] libfdk_aac_jll v2.0.2+0
  [b53b4c65] libpng_jll v1.6.38+0
  [f27f6e37] libvorbis_jll v1.3.7+0
  [1270edf5] x264_jll v2021.5.5+0
  [dfaa095f] x265_jll v3.5.0+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [4607b0f0] SuiteSparse `@stdlib/SuiteSparse`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [05823500] OpenLibm_jll `@stdlib/OpenLibm_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
     Testing Running tests...
   Resolving package versions...
    Updating `/tmp/jl_hhDiTk/Project.toml`
  [d37af2e0] + ReferenceTests v0.1.0 `~/.julia/packages/Makie/gQOQF/ReferenceTests`
    Updating `/tmp/jl_hhDiTk/Manifest.toml`
  [39de3d68] + AxisArrays v0.4.4
  [aafaddc9] + CatIndices v0.2.2
  [324d7699] + CategoricalArrays v0.10.2
  [ed09eef8] + ComputationalResources v0.3.2
  [150eb455] + CoordinateTransformations v0.6.2
  [dc8bdbbb] + CustomUnitRanges v1.0.2
  [b4f34e82] + Distances v0.10.6
  [4f61f5a4] + FFTViews v0.3.2
  [bbac6d45] + IdentityRanges v0.3.1
  [2803e5a7] + ImageAxes v0.6.9
  [f332f351] + ImageContrastAdjustment v0.3.7
  [a09fc81d] ↓ ImageCore v0.9.3 ⇒ v0.8.22
  [51556ac3] + ImageDistances v0.2.13
  [6a3955dd] + ImageFiltering v0.6.21
  [bc367c6b] + ImageMetadata v0.9.5
  [787d08f9] + ImageMorphology v0.2.11
  [2996bd0c] + ImageQualityIndexes v0.2.2
  [4e3cecfd] + ImageShow v0.3.1
  [02fcd773] + ImageTransformations v0.8.13
  [916415d5] + Images v0.24.1
  [9b13fd28] ↓ IndirectArrays v1.0.0 ⇒ v0.5.1
  [1914dd2f] + MacroTools v0.5.9
  [f09324ee] ↓ Netpbm v1.0.2 ⇒ v1.0.1
  [d96e819e] + Parameters v0.12.3
  [b3c3ace0] + RangeArrays v0.3.2
  [d37af2e0] + ReferenceTests v0.1.0 `~/.julia/packages/Makie/gQOQF/ReferenceTests`
  [6038ab10] + Rotations v1.0.4
  [699a6c99] + SimpleTraits v0.9.4
  [860ef19b] + StableRNGs v1.0.0
  [06e1c1a7] + TiledIteration v0.3.1
  [3a884ed6] + UnPack v1.0.2
  [07c12ed4] + ghr_jll v0.13.0+1
  [0dad84c5] ~ ArgTools `@stdlib/ArgTools` ⇒ 
  [56f22d72] ~ Artifacts `@stdlib/Artifacts` ⇒ 
  [2a0f44e3] ~ Base64 `@stdlib/Base64` ⇒ 
  [ade2ca70] ~ Dates `@stdlib/Dates` ⇒ 
  [8bb1440f] ~ DelimitedFiles `@stdlib/DelimitedFiles` ⇒ 
  [8ba89e20] ~ Distributed `@stdlib/Distributed` ⇒ 
  [f43a241f] ~ Downloads `@stdlib/Downloads` ⇒ 
  [9fa8497b] + Future
  [b77e0a4c] ~ InteractiveUtils `@stdlib/InteractiveUtils` ⇒ 
  [4af54fe1] ~ LazyArtifacts `@stdlib/LazyArtifacts` ⇒ 
  [b27032c2] ~ LibCURL `@stdlib/LibCURL` ⇒ 
  [76f85450] ~ LibGit2 `@stdlib/LibGit2` ⇒ 
  [8f399da3] ~ Libdl `@stdlib/Libdl` ⇒ 
  [37e2e46d] ~ LinearAlgebra `@stdlib/LinearAlgebra` ⇒ 
  [56ddb016] ~ Logging `@stdlib/Logging` ⇒ 
  [d6f4376e] ~ Markdown `@stdlib/Markdown` ⇒ 
  [a63ad114] ~ Mmap `@stdlib/Mmap` ⇒ 
  [ca575930] ~ NetworkOptions `@stdlib/NetworkOptions` ⇒ 
  [de0858da] ~ Printf `@stdlib/Printf` ⇒ 
  [3fa0cd96] ~ REPL `@stdlib/REPL` ⇒ 
  [9a3f8284] ~ Random `@stdlib/Random` ⇒ 
  [ea8e919c] ~ SHA `@stdlib/SHA` ⇒ 
  [9e88b42a] ~ Serialization `@stdlib/Serialization` ⇒ 
  [1a1011a3] ~ SharedArrays `@stdlib/SharedArrays` ⇒ 
  [6462fe0b] ~ Sockets `@stdlib/Sockets` ⇒ 
  [2f01184e] ~ SparseArrays `@stdlib/SparseArrays` ⇒ 
  [10745b16] ~ Statistics `@stdlib/Statistics` ⇒ 
  [4607b0f0] ~ SuiteSparse `@stdlib/SuiteSparse` ⇒ 
  [fa267f1f] ~ TOML `@stdlib/TOML` ⇒ 
  [a4e569a6] ~ Tar `@stdlib/Tar` ⇒ 
  [cf7118a7] ~ UUIDs `@stdlib/UUIDs` ⇒ 
  [4ec0a83e] ~ Unicode `@stdlib/Unicode` ⇒ 
  [e66e0078] ~ CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll` ⇒ 
  [deac9b47] ~ LibCURL_jll `@stdlib/LibCURL_jll` ⇒ 
  [29816b5a] ~ LibSSH2_jll `@stdlib/LibSSH2_jll` ⇒ 
  [c8ffd9c3] ~ MbedTLS_jll `@stdlib/MbedTLS_jll` ⇒ 
  [14a3606d] ~ MozillaCACerts_jll `@stdlib/MozillaCACerts_jll` ⇒ 
  [05823500] ~ OpenLibm_jll `@stdlib/OpenLibm_jll` ⇒ 
  [83775a58] ~ Zlib_jll `@stdlib/Zlib_jll` ⇒ 
  [8e850ede] ~ nghttp2_jll `@stdlib/nghttp2_jll` ⇒ 
  [3f19e933] ~ p7zip_jll `@stdlib/p7zip_jll` ⇒ 
Window handling: Test Failed at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:16
  Expression: screen === screen2
   Evaluated: GLMakie.Screen(...) === GLMakie.Screen(...)
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:16 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:11 [inlined]
 [4] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] top-level scope
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:10
Window handling: Test Failed at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:18
  Expression: getscreen(ax.scene) === screen
   Evaluated: GLMakie.Screen(...) === GLMakie.Screen(...)
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:18 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:11 [inlined]
 [4] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] top-level scope
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:10
Window handling: Test Failed at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:22
  Expression: getscreen(ax.scene) === nothing
   Evaluated: GLMakie.Screen(...) === nothing
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:22 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:11 [inlined]
 [4] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] top-level scope
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:10
Window handling: Test Failed at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:23
  Expression: !((events(ax.scene)).window_open[])
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:23 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:11 [inlined]
 [4] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] top-level scope
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:10
WARNING: importing deprecated binding GeometryBasics.FRect into Makie.
WARNING: importing deprecated binding GeometryBasics.FRect2D into Makie.
WARNING: importing deprecated binding GeometryBasics.FRect3D into Makie.
WARNING: importing deprecated binding GeometryBasics.IRect into Makie.
WARNING: importing deprecated binding GeometryBasics.IRect2D into Makie.
WARNING: importing deprecated binding GeometryBasics.IRect3D into Makie.
WARNING: importing deprecated binding GeometryBasics.Point2f0 into Makie.
WARNING: importing deprecated binding GeometryBasics.Point3f0 into Makie.
WARNING: importing deprecated binding GeometryBasics.Point4f0 into Makie.
WARNING: importing deprecated binding GeometryBasics.Rect2D into Makie.
WARNING: importing deprecated binding GeometryBasics.Rect3D into Makie.
WARNING: importing deprecated binding GeometryBasics.Vec2f0 into Makie.
WARNING: importing deprecated binding GeometryBasics.Vec3f0 into Makie.
WARNING: importing deprecated binding GeometryBasics.Vec4f0 into Makie.
Window handling: Test Failed at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:24
  Expression: isempty((events(ax.scene)).window_open.listeners)
   Evaluated: isempty(Pair{Int8, Vector{Makie.PrioCallback}}[127 => [Makie.PrioCallback(Makie.var"#901#903"{Scene, GLMakie.Screen}(Scene (1276px, 424px):
  18 Plots:
    ├ Combined{Makie.poly, Tuple{Vector{Vector{Point{2, Float32}}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ MakieCore.Text{Tuple{String}}
    ├ Lines{Tuple{Vector{Point{2, Float32}}}}
    ├ MakieCore.Text{Tuple{Vector{Tuple{AbstractString, Point{2, Float32}}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ LineSegments{Tuple{Vector{Point{2, Float32}}}}
    ├ MakieCore.Text{Tuple{String}}
    ├ Lines{Tuple{Vector{Point{2, Float32}}}}
    ├ MakieCore.Text{Tuple{Vector{Tuple{AbstractString, Point{2, Float32}}}}}
    ├ Lines{Tuple{Vector{Point{2, Float32}}}}
    ├ Lines{Tuple{Vector{Point{2, Float32}}}}
    └ MakieCore.Text{Tuple{String}}
  1 Child Scene:
    └ Scene (1225px, 365px), GLMakie.Screen(...), Core.Box(Observables.ObserverFunction(Makie.PrioCallback(#= circular reference @-4 =#), PriorityObservable(true), false))))]])
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:24 [inlined]
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] macro expansion
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:11 [inlined]
 [4] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [5] top-level scope
   @ ~/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:10
Test Summary:                                             | Pass  Fail  Total
unit tests                                                |    4     5      9
  Window handling                                         |    1     5      6
  Pick a plot element or plot elements inside a rectangle |    3            3
ERROR: LoadError: LoadError: Some tests did not pass: 4 passed, 5 failed, 0 errored, 0 broken.
in expression starting at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/unit_tests.jl:9
in expression starting at /home/jaustar/.julia/packages/GLMakie/pFGSp/test/runtests.jl:13
ERROR: Package GLMakie errored during testing

```

**Comment by SimonDanisch** [comment] 2021-11-12 15:40
Hm, that looks like a problem with  i3  - because I just checked with `]activate --temp; add GLMakie; test GLMakie` on 1.6.3, that everything works, and it seems to have problems with the created screen...Can you run something like `scatter(1:4)` in the REPL, to see what exactly happens?

**Comment by ajaust** [comment] 2021-11-12 15:48
I attached a screenshot of the window I get. This looks fine to me (?!). However, the window and plot creation felt quite slow to me (took about 1 minute or so). I am new to Julia so I cannot really judge how fast/slow this should be.

![2021-11-12-julia-scatter-screenshot](https://user-images.githubusercontent.com/18347253/141494440-ad34563e-9240-4316-a2ac-06ed1bbb64a4.png)

**Comment by SimonDanisch** [comment] 2021-11-12 16:13
>It also seems I cannot properly close this window with either CTRL-Q nor Alt-F4.

Hm, does it work by pressing the `x` button?
The tests that are failing for you are partly about closing the screen, so makes sense that something is wonky there... But, I guess the rest will work fine then.

> I am new to Julia so I cannot really judge how fast/slow this should be.

That's the dreaded time to first plot... Lots has been said about this, but the current workaround is to keep the julia process running as long as possible, by using e.g. VSCode, which allows you to dynamically program in Julia and change code without restarting, or using [Revise.jl](https://github.com/timholy/Revise.jl)

**Comment by ajaust** [comment] 2021-11-12 16:26
Thanks for the quick response and the explanation.

> Hm, does it work by pressing the `x` button? The tests that are failing for you are partly about closing the screen, so makes sense that something is wonky there... But, I guess the rest will work fine then.

There is no `x` button on i3 as it draws windows with minimal ornaments. The idea is to not waste any space on the screen, but rather bind such actions to keyboard shortcuts. The window in the screenshot is all of the window I get. The options for "maximize/minimize window" or "set window to fullscreen" that are common are not available from the window frame either. Closing the window with `xkill` works, but it also kills the REPL since the connection to the X server is disrupted.

```
X connection to :0 broken (explicit kill or server shutdown).
```

> That's the dreaded time to first plot.

Then I will accept this. I was just unsure whether that was part of the problem I observe or not.

Maybe a "stupid" follow up question, if I would like to have to support windows by using `CTRL-Q`, `ALT-F4` or some other shortcut, would this be a feature to discuss here or in another repository (some dependency?)/issue?

**Comment by SimonDanisch** [comment] 2021-11-12 16:50
>Maybe a "stupid" follow up question, if I would like to have to support windows by using CTRL-Q, ALT-F4 or some other shortcut, would this be a feature to discuss here or in another repository (some dependency?)/issue?

This has to be a bug, since this works just fine on my PC... I searched the GLFW repository https://github.com/glfw/glfw for issues like that but couldn't find one (that's the windowing library GLMakie uses)...
Maybe google can give more answers for e.g. `X connection to :0 broken (explicit kill or server shutdown).` or some other search terms...

**Comment by ajaust** [comment] 2021-11-12 17:03
Using `mod+shift+q` with the window active closes the window as expected. I just forgot about that i3 shortcut. 

It still appears weird to me that the other shortcuts work for you, but not for me. Is there anything (reasonable) we can to fix the failing tests? Otherwise, would it make sense to leave this issue open or document this behavior somewhere else for other users?

**Comment by fatteneder** [comment] 2022-01-19 19:16
Hi.

I receive the same errors, but I am on a different Linux distribution (Void Linux) and I also use a different window manager (`bspwm`).
I tried it with Julia 1.6.4 and 1.7.1, both download from the Julia website:
```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
```

Perhaps its not a `i3` issue but maybe something `xserver` related?

**Comment by fatteneder** [comment] 2022-01-20 20:03
I did some debugging and I think I found a potential issue:
Just like @ajaust said above, `i3` (and also `bspwm`) tend to make windows spacing filling if possible, hence, they resize them automatically.
If I toggle off automatic resizing, e.g. enable floating windows, then running the following part inside the REPL works, except the last line gives `false`: 
https://github.com/JuliaPlots/Makie.jl/blob/8e07051d065f2505680bac28ce084d16ea1fbac3/GLMakie/test/unit_tests.jl#L11-L24

I think the cause is this piece of code:
https://github.com/JuliaPlots/Makie.jl/blob/8e07051d065f2505680bac28ce084d16ea1fbac3/GLMakie/src/screen.jl#L406-L412

Because it instructs to **DESTROY** the window if it was resized, which `i3` and `bspwm` do by default, the two screen objects deviate in the test.

Is it really necessary to destroy the screen if resolutions don't match?

PS: I couldn't figure out how to `dev GLMakie`, but I receive an error "Error: name 'Makie' given by project fiel ... does not match given name 'GLMakie'.
I also tried `dev Makie` and then editing `~/.julia/dev/Makie/GLMakie/test/unit_test.jl` but that also did not work. What is the right way to work with this monorepo?

**Comment by fatteneder** [comment] 2022-06-17 22:48
#1771 got rid off the `destroy!(screen)` call.
This now fixed the `screen == screen2` issue that started this thread.

But now the "Pick a plot element or plot elements inside a rectangle" fail:
https://github.com/JuliaPlots/Makie.jl/blob/c63dc07f8e62f48e65d40d33f55bdebbf672b712/GLMakie/test/unit_tests.jl#L66-L92

Again, it is the automatic tiling that messes things about, because depending on how the window is resized the pick is done within or without bounds.


PS: Tested now on Fedora 36 using `bspwm` and automatic window tiling enabled. The tests still pass with floating mode enabled.

**Comment by asinghvi17** [comment] 2022-06-18 03:46
Seealso #2063

**Comment by ffreyer** [comment] 2024-08-22 22:23
Closing this since it sounds like it's fixed

**Closed by ffreyer** 2024-08-22 22:23 UTC
