### ISSUE TITLE
Add `axislegend!`

### ISSUE THREAD

**Issue by jariji** [MakieOrg/Makie.jl#3676] opened 2024-03-04 07:45 UTC
For a lot of functions, if it takes an axis, it's got a `!` in the name. So when I want to pass an axis to `axislegend`, I assumed it would be `axislegend!` but that doesn't exist. Should it exist?

**Comment by ffreyer** [comment] 2024-08-27 14:54
Closing as duplicate of #3258

**Closed by ffreyer** 2024-08-27 14:54 UTC
Labels: enhancement
