### ISSUE TITLE
Lineplot not rendered properly in GLMakie

### ISSUE THREAD

**Issue by martincornejo** [MakieOrg/Makie.jl#4582] opened 2024-11-11 14:30 UTC
## MWE
```julia
using GLMakie
x = cumsum(randn(10_000)) .+ rand.()
lines(x)
```

## Output GLMakie
![Image](https://github.com/user-attachments/assets/07dfa0f8-6629-48d4-a559-837517f1aadd)

## Output CairoMakie
![Image](https://github.com/user-attachments/assets/099a9825-55c8-428b-b004-0cead6eba8ed)

```
  [13f3f980] CairoMakie v0.12.16
  [e9467ef8] GLMakie v0.10.16
  [ee78f7c6] Makie v0.21.16
```

```
julia> versioninfo()
Julia Version 1.11.1
Commit 8f5b7ca12a (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 4800H with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
```

**Comment by martincornejo** [comment] 2024-11-11 14:38
When zooming in, the wrongly rendered *features* gradually dissapear

**Comment by SimonDanisch** [comment] 2024-11-11 15:51
Duplicate of: https://github.com/MakieOrg/Makie.jl/issues/3906

**Closed by SimonDanisch** 2024-11-11 15:51 UTC
Labels: bug
