### ISSUE TITLE
`xticks!` fails to find the axis even though it exists

### ISSUE THREAD

**Issue by Sagnac** [MakieOrg/Makie.jl#3463] opened 2023-12-11 19:46 UTC
```julia
using GLMakie # v0.9.3
fig = Figure()
axis = Axis(fig[1,1])
xticks!(fig.scene; xtickrange = 0:8)
```
returns
```julia
ERROR: AssertionError: The Scene does not have an axis!
```
The tick functions don't seem to have methods for `Axis`, only `Scene`

**Comment by ffreyer** [comment] 2024-08-26 20:17
Closing as duplicate of #1344

**Closed by ffreyer** 2024-08-26 20:17 UTC
Labels: bug, old vs new
