### ISSUE TITLE
Saving videos does not conserve transparent background

### ISSUE THREAD

**Issue by Datseris** [MakieOrg/Makie.jl#1825] opened 2022-04-18 12:01 UTC
Saving a video with `record` and CairoMakie.jl does not respect the transparent background. I guess a MWE would be
```julia
using CairoMakie
fig = Figure(backgroundcolor = :transparent)
lines!(fig[1,1], rand(5), rand(5))
record("test.mp4", fig, 1:3) do i
end
```

**Comment by asinghvi17** [comment] 2022-04-29 03:55
See also #518

**Comment by ffreyer** [comment] 2024-08-23 10:37
Closing as duplicate of #518

**Closed by ffreyer** 2024-08-23 10:37 UTC
