### ISSUE TITLE
`merge(::Theme, ::Theme)` should be the other way round

### ISSUE THREAD

**Issue by nathanaelbosch** [MakieOrg/Makie.jl#2913] opened 2023-05-04 06:07 UTC
The docstrings of `merge` for e.g. `NamedTuple`s contains the following example:
```
julia> merge((a=1, b=2, c=3), (b=4, d=5))
  (a = 1, b = 4, c = 3, d = 5)
```
That is, the second argument overwrites the values of the first argument.

This is not the case for `Theme`s:
```
julia> merge(MakieCore.Theme(a=1, b=1), MakieCore.Theme(b=2, c=2))
Attributes with 3 entries:
  a => 1
  b => 1
  c => 2
```

I think this should be changed such that the behaviour is compatible with the behaviour for `NamedTuple`s and `AbstractDict`s since users probably expect it to behave the same.

**Comment by nathanaelbosch** [comment] 2023-05-04 06:11
This is probably the part that should be adjusted: 
https://github.com/MakieOrg/Makie.jl/blob/1f91e94dac8487aba9697c2bb15506606842a8a8/MakieCore/src/attributes.jl#L246-L260
If this is indeed something that should be changed I could go ahead and draft a PR.

**Comment by SimonDanisch** [comment] 2023-05-04 08:42
Yeah this is a bit unfortunate..
I think it comes from the fact, that for `merge!` the order in base is wrong for merging themes, and from there it poisoned the other functions.

> I could go ahead and draft a PR.

That would be nice, but I think this will need more work then expected, with `merge`/`merge!` being used a lot and the need to figure out what to do about `merge!(target, defaults)`.

**Comment by ffreyer** [comment] 2024-08-24 19:22
Closing as duplicate of #1939

**Closed by ffreyer** 2024-08-24 19:22 UTC
