### ISSUE TITLE
DataInspector doesn't show next to curve for non-identity axis scales

### ISSUE THREAD

**Issue by kevjzheng** [MakieOrg/Makie.jl#4018] opened 2024-07-11 04:48 UTC
When DataInspector is enabled for a figure where axis.xscale = log10 for example, the data label doesn't show properly at the right place.

My current workaround is to manually plot the data (x,y) with
lines!(ax, log10(x), y, inspector_label = (self, i, p) => string(10^p[1]) * "," * string(p[2])) 

Is there something I am missing or it's indeed a bug with DataInspector for non-identity scales?

**Comment by ffreyer** [comment] 2024-08-28 15:28
Closing this as duplicate of #3571

**Closed by ffreyer** 2024-08-28 15:28 UTC
Labels: bug, transformation, DataInspector
