### ISSUE TITLE
Installation of GLMakie on Ubuntu 24.04 fails

### ISSUE THREAD

**Issue by ufechner7** [MakieOrg/Makie.jl#4002] opened 2024-07-02 07:45 UTC
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
```
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 7840U w/ Radeon  780M Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```

I did:
```
mkdir glmakie
cd glmakie
julia --project="."
```
and then in Julia
```
using Pkg
Pkg.add("GLMakie")
```
This results in the following error:
```
julia> err
PkgPrecompileError: The following 1 direct dependency failed to precompile:

GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]

Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to "/home/ufechner/.julia/compiled/v1.10/GLMakie/jl_zBkn6i".
Failed to load plugin: '/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: hb_ot_color_has_paint'
No plugins found, falling back on no decorations
┌ Warning:     GLFW couldn't create an OpenGL window.
│     This likely means, you don't have an OpenGL capable Graphic Card,
│     or you don't have an OpenGL 3.3 capable video driver installed.
│     Have a look at the troubleshooting section in the GLMakie readme:
│     https://github.com/MakieOrg/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
└ @ GLMakie ~/.julia/packages/GLMakie/ebMDx/src/screen.jl:250
ERROR: LoadError: GLFWError (API_UNAVAILABLE): EGL: Failed to get EGL display: Success
Stacktrace:
  [1] _ErrorCallbackWrapper(code::Int32, description::Cstring)
    @ GLFW ~/.julia/packages/GLFW/BWxfF/src/callback.jl:43
  [2] CreateWindow(width::Int64, height::Int64, title::String, monitor::GLFW.Monitor, share::GLFW.Window)
    @ GLFW ~/.julia/packages/GLFW/BWxfF/src/glfw3.jl:499
  [3] GLFW.Window(; name::String, resolution::Tuple{Int64, Int64}, debugging::Bool, major::Int64, minor::Int64, windowhints::Vector{Tuple{UInt32, Integer}}, contexthints::Vector{Tuple{UInt32, Integer}}, visible::Bool, focus::Bool, fullscreen::Bool, monitor::Nothing, share::GLFW.Window)
    @ GLFW ~/.julia/packages/GLFW/BWxfF/src/glfw3.jl:344
  [4] Window
    @ ~/.julia/packages/GLFW/BWxfF/src/glfw3.jl:302 [inlined]
  [5] empty_screen(debugging::Bool; reuse::Bool)
    @ GLMakie ~/.julia/packages/GLMakie/ebMDx/src/screen.jl:241
  [6] empty_screen
    @ ~/.julia/packages/GLMakie/ebMDx/src/screen.jl:222 [inlined]
  [7] singleton_screen(debugging::Bool)
    @ GLMakie ~/.julia/packages/GLMakie/ebMDx/src/screen.jl:329
  [8] macro expansion
    @ ~/.julia/packages/GLMakie/ebMDx/src/precompiles.jl:21 [inlined]
  [9] macro expansion
    @ ~/.julia/packages/PrecompileTools/L8A3n/src/workloads.jl:78 [inlined]
 [10] macro expansion
    @ ~/.julia/packages/GLMakie/ebMDx/src/precompiles.jl:18 [inlined]
 [11] macro expansion
    @ ~/.julia/packages/PrecompileTools/L8A3n/src/workloads.jl:140 [inlined]
 [12] top-level scope
    @ ~/.julia/packages/GLMakie/ebMDx/src/precompiles.jl:16
 [13] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [14] include(x::String)
    @ GLMakie ~/.julia/packages/GLMakie/ebMDx/src/GLMakie.jl:1
 [15] top-level scope
    @ ~/.julia/packages/GLMakie/ebMDx/src/GLMakie.jl:89
 [16] include
    @ ./Base.jl:495 [inlined]
 [17] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2222
 [18] top-level scope
    @ stdin:3
in expression starting at /home/ufechner/.julia/packages/GLMakie/ebMDx/src/precompiles.jl:15
in expression starting at /home/ufechner/.julia/packages/GLMakie/ebMDx/src/GLMakie.jl:1
in expression starting at stdin:3
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF-8" (mapped to "en_US.UTF-8")
GLFWError (PLATFORM_ERROR): Wayland: Failed to create XKB compose table
Stacktrace:
 [1] _ErrorCallbackWrapper(code::Int32, description::Cstring)
   @ GLFW ~/.julia/packages/GLFW/BWxfF/src/callback.jl:43
 [2] Terminate()
   @ GLFW ~/.julia/packages/GLFW/BWxfF/src/glfw3.jl:443
 [3] _atexit(exitcode::Int32)
   @ Base ./initdefs.jl:428
 [4] exit
   @ ./initdefs.jl:28 [inlined]
 [5] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:323
 [6] _start()
   @ Base ./client.jl:552

julia> 
```

**Comment by ufechner7** [comment] 2024-07-02 07:46
The following workaround fixes the issue:

Add the following lines to Project.toml:

```
[deps]
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"

[compat]
GLFW_jll = "=3.3.9"
```

**Comment by PhyX-Meow** [comment] 2024-07-02 09:34
Same issue here, seem that glfw 3.4.0 cause the problem.

**Comment by SimonDanisch** [comment] 2024-07-02 13:59
Duplicate of https://github.com/MakieOrg/Makie.jl/issues/3997

**Comment by ufechner7** [comment] 2024-07-02 16:02
@SimonDanisch Please re-open this issue. It is NOT Mac OS related and cannot be fixed by changing code that is Mac OS only.

**Comment by SimonDanisch** [comment] 2024-07-02 16:32
Oh sorry, you're right...

**Comment by SimonDanisch** [comment] 2024-07-07 12:12
This should have fixed it: https://github.com/JuliaGL/GLFW.jl/pull/238

**Closed by SimonDanisch** 2024-07-07 12:12 UTC
Labels: bug

**Comment by ufechner7** [comment] 2024-07-08 11:06
Please, reopen this issue. It is NOT fixed by https://github.com/JuliaGL/GLFW.jl/pull/238 .

**Comment by SimonDanisch** [comment] 2024-07-08 11:17
Did the error message change?

**Comment by cyanescent** [comment] 2024-07-08 11:49
Strange, I got the exact same error message, also on Linux (arch-based), slightly older AMD with iGPU, official julia build, but https://github.com/JuliaGL/GLFW.jl/pull/238 did solve the bug, after removing the suggested workaround in Project.toml and updating.

**Comment by ufechner7** [comment] 2024-07-08 13:07
I have to correct myself, the issue seams to be fixed when using the latest version of GLFW. Sorry for the noise.
