### ISSUE TITLE
Precompile error on Raspberry Pi (WGLMakie 0.8.15)

### ISSUE THREAD

**Issue by KronosTheLate** [MakieOrg/Makie.jl#3278] opened 2023-10-05 12:21 UTC
I am not sure how interesting backwards compatability is, but when I install WGLMakie on a raspberry Pi 4, i get version 0.8.15. That version fails to precompile. The issue seems to be rather mundane. From the stacktrace:
```
ERROR: LoadError: LoadError: LoadError: DomainError with -1.699445855e9:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
```

The enviroment was fresh, except for the other packages seen from `] st`. The julia version is the LTS (1.6.7), and is also freshly installed.

<details>
<summary>Stacktrace</summary>

```
Precompiling project...
  ✗ WGLMakie
  0 dependencies successfully precompiled in 338 seconds (262 already precompiled)

ERROR: The following 1 direct dependency failed to precompile:

WGLMakie [276b4fcb-3e11-5398-bf8b-a0c2d153d008]

Failed to precompile WGLMakie [276b4fcb-3e11-5398-bf8b-a0c2d153d008] to /home/thetaoptec/.julia/compiled/v1.6/WGLMakie/jl_4zeJyM.
ERROR: LoadError: LoadError: LoadError: DomainError with -1.699445855e9:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
  [1] throw_complex_domainerror(f::Symbol, x::Float64)
    @ Base.Math ./math.jl:33
  [2] sqrt
    @ ./math.jl:582 [inlined]
  [3] sqrt
    @ ./math.jl:608 [inlined]
  [4] _broadcast_getindex_evalf
    @ ./broadcast.jl:648 [inlined]
  [5] _broadcast_getindex
    @ ./broadcast.jl:621 [inlined]
  [6] _getindex
    @ ./broadcast.jl:644 [inlined]
  [7] _broadcast_getindex
    @ ./broadcast.jl:620 [inlined]
  [8] getindex
    @ ./broadcast.jl:575 [inlined]
  [9] macro expansion
    @ ./broadcast.jl:984 [inlined]
 [10] macro expansion
    @ ./simdloop.jl:77 [inlined]
 [11] copyto!
    @ ./broadcast.jl:983 [inlined]
 [12] copyto!
    @ ./broadcast.jl:936 [inlined]
 [13] copy
    @ ./broadcast.jl:908 [inlined]
 [14] materialize
    @ ./broadcast.jl:883 [inlined]
 [15] sdf(img::Matrix{Bool})
    @ SignedDistanceFields ~/.julia/packages/SignedDistanceFields/RNoSO/src/SignedDistanceFields.jl:63
 [16] sdf
    @ ~/.julia/packages/SignedDistanceFields/RNoSO/src/SignedDistanceFields.jl:64 [inlined]
 [17] sdistancefield(img::Matrix{UInt8}, downsample::Int32, pad::Int32)
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:351
 [18] render(atlas::Makie.TextureAtlas, b::Makie.BezierPath)
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:404
 [19] (::Makie.var"#55#56"{Makie.TextureAtlas, Makie.BezierPath})()
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:309
 [20] get!(default::Makie.var"#55#56"{Makie.TextureAtlas, Makie.BezierPath}, h::Dict{UInt32, Int64}, key::UInt32)
    @ Base ./dict.jl:465
 [21] insert_glyph!
    @ ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:308 [inlined]
 [22] insert_glyph!(atlas::Makie.TextureAtlas, path::Makie.BezierPath)
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:303
 [23] glyph_index!
    @ ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:283 [inlined]
 [24] glyph_uv_width!
    @ ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:291 [inlined]
 [25] bezierpath_pad_scale_factor(atlas::Makie.TextureAtlas, bp::Makie.BezierPath)
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:480
 [26] marker_scale_factor(atlas::Makie.TextureAtlas, path::Makie.BezierPath)
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:493
 [27] rescale_marker(atlas::Makie.TextureAtlas, pathmarker::Makie.BezierPath, font::FreeTypeAbstraction.FTFont, markersize::Vector{GeometryBasics.Vec{2, Float32}})
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:497
 [28] map(::typeof(Makie.rescale_marker), ::Observables.Observable{Makie.TextureAtlas}, ::Observables.Observable{Makie.BezierPath}, ::Vararg{Any, N} where N; ignore_equal_values::Bool)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:564
 [29] marker_attributes(atlas::Makie.TextureAtlas, marker::Observables.Observable{Makie.BezierPath}, markersize::Observables.Observable{Vector{GeometryBasics.Vec{2, Float32}}}, font::Observables.Observable{FreeTypeAbstraction.FTFont}, marker_offset::Observables.Observable{Any})
    @ Makie ~/.julia/packages/Makie/NrrbP/src/utilities/texture_atlas.jl:557
 [30] scatter_shader(scene::Makie.Scene, attributes::Dict{Symbol, Observables.Observable}, plot::MakieCore.Scatter{Tuple{Vector{GeometryBasics.Point{2, Float32}}}})
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/particles.jl:137
 [31] create_shader(scene::Makie.Scene, plot::MakieCore.Scatter{Tuple{Vector{GeometryBasics.Point{2, Float32}}}})
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/particles.jl:223
 [32] serialize_three(scene::Makie.Scene, plot::MakieCore.Scatter{Tuple{Vector{GeometryBasics.Point{2, Float32}}}})
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/serialization.jl:320
 [33] serialize_plots(scene::Makie.Scene, plots::Vector{MakieCore.AbstractPlot}, result::Vector{Any})
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/serialization.jl:309
 [34] serialize_plots
    @ ~/.julia/packages/WGLMakie/VkJZh/src/serialization.jl:306 [inlined]
 [35] serialize_scene(scene::Makie.Scene)
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/serialization.jl:293
 [36] (::WGLMakie.var"#50#55")(child::Makie.Scene)
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/serialization.jl:291
 [37] iterate(::Base.Generator{Vector{Makie.Scene}, WGLMakie.var"#50#55"})
    @ Base ./generator.jl:47
 [38] _collect(c::Vector{Makie.Scene}, itr::Base.Generator{Vector{Makie.Scene}, WGLMakie.var"#50#55"}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:695
 [39] collect_similar(cont::Vector{Makie.Scene}, itr::Base.Generator{Vector{Makie.Scene}, WGLMakie.var"#50#55"})
    @ Base ./array.jl:606
 [40] map(f::Function, A::Vector{Makie.Scene})
    @ Base ./abstractarray.jl:2294
 [41] serialize_scene(scene::Makie.Scene)
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/serialization.jl:291
--- the last 6 lines are repeated 1 more time ---
 [48] three_display(session::JSServe.Session{JSServe.NoConnection}, scene::Makie.Scene; screen_config::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/three_plot.jl:43
 [49] three_display(session::JSServe.Session{JSServe.NoConnection}, scene::Makie.Scene)
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/three_plot.jl:42
 [50] top-level scope
    @ ~/.julia/packages/WGLMakie/VkJZh/src/precompiles.jl:13
 [51] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
 [52] include
    @ ~/.julia/packages/WGLMakie/VkJZh/src/WGLMakie.jl:1 [inlined]
 [53] macro expansion
    @ ~/.julia/packages/WGLMakie/VkJZh/src/precompiles.jl:29 [inlined]
 [54] macro expansion
    @ ~/.julia/packages/PrecompileTools/kmH5L/src/workloads.jl:85 [inlined]
 [55] top-level scope
    @ ~/.julia/packages/WGLMakie/VkJZh/src/precompiles.jl:24
 [56] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
 [57] include(x::String)
    @ WGLMakie ~/.julia/packages/WGLMakie/VkJZh/src/WGLMakie.jl:1
 [58] top-level scope
    @ ~/.julia/packages/WGLMakie/VkJZh/src/WGLMakie.jl:92
 [59] include
    @ ./Base.jl:384 [inlined]
 [60] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1235
 [61] top-level scope
    @ none:1
 [62] eval
    @ ./boot.jl:360 [inlined]
 [63] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
in expression starting at /home/thetaoptec/.julia/packages/Makie/NrrbP/precompile/shared-precompile.jl:6
in expression starting at /home/thetaoptec/.julia/packages/WGLMakie/VkJZh/src/precompiles.jl:23
in expression starting at /home/thetaoptec/.julia/packages/WGLMakie/VkJZh/src/WGLMakie.jl:1
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
 [2] precompile(ctx::Pkg.Types.Context; internal_call::Bool, strict::Bool, warn_loaded::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1265
 [3] precompile
   @ /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:921 [inlined]
 [4] #precompile#196
   @ /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:919 [inlined]
 [5] precompile()
   @ Pkg.API /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:919
 [6] top-level scope
   @ REPL[21]:1
```
</details>

<details>
<summary>Version information</summary>

```
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [717857b8] DSP v0.7.9
  [08be435b] EasyFFTs v0.3.0 `~/.julia/dev/EasyFFTs`
  [ff932bff] PSDTools v1.0.0-DEV `~/.julia/dev/PSDTools`
  [c3e4b0f8] Pluto v0.19.29
  [7f904dfe] PlutoUI v0.7.52
  [295af30f] Revise v3.5.6
  [276b4fcb] WGLMakie v0.8.15

julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 3 (v7l)
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cortex-a72)
```
</details>

**Comment by SimonDanisch** [comment] 2023-10-05 12:29
I guess most such issues should be easy to fix by anyone knowing a bit of Julia, so feel free to investigate :) 
Pretty sure nobody else will for now, since most don't even have the hardware ;)

**Comment by KronosTheLate** [comment] 2023-10-05 18:03
Right. Makie precompilation actually takes so long on a RPi, and I just discovered PlutoPlotly which works great, so I am unlikely to be using WGLMakie on the RPi further. Do you thing this issue should be kept around, as it does seem like a legitimate issue, or is it low enough priority that it warrents closing a legit issue?

**Comment by SimonDanisch** [comment] 2023-10-05 20:09
Guess it can't hurt to leave it open... we plan to move a lot to js which should help with the compile times, but I guess PlutoPlotly will be pretty unbeatable for now ;)

**Comment by ffreyer** [comment] 2024-08-26 14:53
Closing as duplicate of #477.

**Closed by ffreyer** 2024-08-26 14:53 UTC
Labels: bug, WGLMakie
