### ISSUE TITLE
Error when plotting line with closely spaced (?) data 

### ISSUE THREAD

**Issue by jonaswickman** [MakieOrg/Makie.jl#2967] opened 2023-05-19 20:10 UTC
The following code:
```
fig = Figure()

x = [100.0, 300.0]
y = [1.00000021091221, 1.0000006393760357]

ax = Axis( fig[1,1] )
lines!( x , y )
fig
```
Produces the following error:
```
ERROR: ArgumentError: range step cannot be zero
Stacktrace:
  [1] (::Colon)(start::Float32, step::Float32, stop::Float32)
    @ Base ./twiceprecision.jl:396
  [2] get_minor_tickvalues(i::IntervalsBetween, scale::Function, tickvalues::Vector{Float32}, vmin::Float32, vmax::Float32)
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/lineaxis.jl:705
  [3] (::Makie.var"#1275#1289"{Attributes, Observable{Vector{Float32}}, Observable{Tuple{Float32, Float32}}})(tickvalues::Vector{Float32}, minorticks::IntervalsBetween)
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/lineaxis.jl:434
  [4] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
  [5] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
  [6] (::Observables.OnAny)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:415
  [7] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
  [8] invokelatest
    @ ./essentials.jl:813 [inlined]
  [9] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [10] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [11] update_tickpos_string(closure_args::Tuple{Observable{Vector{Any}}, Observable{Vector{Point{2, Float32}}}, Observable{Vector{Float32}}, Observable{Tuple{Float32, Tuple{Float32, Float32}, Bool}}, Observable{Tuple{Float32, Float32}}}, tickvalues_labels_unfiltered::Tuple{Vector{Float32}, Vector{Any}}, reversed::Bool, scale::typeof(identity))
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/lineaxis.jl:209
 [12] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
 [13] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
 [14] (::Observables.OnAny)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:415
 [15] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [16] invokelatest
    @ ./essentials.jl:813 [inlined]
 [17] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [18] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [19] (::Observables.MapCallback)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:431
--- the last 5 lines are repeated 1 more time ---
 [25] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [26] invokelatest
    @ ./essentials.jl:813 [inlined]
 [27] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [28] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [29] (::Observables.SetindexCallback)(x::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:111
 [30] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [31] invokelatest
    @ ./essentials.jl:813 [inlined]
 [32] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [33] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [34] (::Observables.MapCallback)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:431
 [35] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [36] invokelatest
    @ ./essentials.jl:813 [inlined]
 [37] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [38] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [39] adjustlimits!(la::Axis)
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:996
 [40] (::Makie.var"#1333#1363"{Axis})(pxa::GeometryBasics.HyperRectangle{2, Int64}, lims::GeometryBasics.HyperRectangle{2, Float32})
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:514
 [41] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:816
 [42] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:813
 [43] (::Observables.OnAny)(value::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:415
 [44] #invokelatest#2
    @ ./essentials.jl:816 [inlined]
 [45] invokelatest
    @ ./essentials.jl:813 [inlined]
 [46] notify
    @ ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:169 [inlined]
 [47] setindex!(observable::Observable, val::Any)
    @ Observables ~/.julia/packages/Observables/PHGQ8/src/Observables.jl:86
 [48] reset_limits!(ax::Axis; xauto::Bool, yauto::Bool, zauto::Bool)
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:646
 [49] reset_limits!
    @ ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:563 [inlined]
 [50] #plot!#1389
    @ ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:799
 [51] plot!(::Axis, ::Type{Lines}, ::Attributes, ::Vector{Float64}, ::Vector{Float64})
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:779
 [52] plot!(::Type{Lines}, ::Axis, ::Vector{Float64}, ::Vararg{Vector{Float64}}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:809
 [53] plot!(::Type{Lines}, ::Axis, ::Vector{Float64}, ::Vector{Float64})
    @ Makie ~/.julia/packages/Makie/DekzU/src/makielayout/blocks/axis.jl:807
 [54] plot!(::Type{Lines}, ::Vector{Float64}, ::Vararg{Vector{Float64}}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/DekzU/src/figureplotting.jl:69
 [55] plot!(::Type{Lines}, ::Vector{Float64}, ::Vector{Float64})
    @ Makie ~/.julia/packages/Makie/DekzU/src/figureplotting.jl:64
 [56] lines!(::Vector{Float64}, ::Vararg{Vector{Float64}}; attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ MakieCore ~/.julia/packages/MakieCore/6sckc/src/recipes.jl:38
 [57] lines!(::Vector{Float64}, ::Vararg{Vector{Float64}})
    @ MakieCore ~/.julia/packages/MakieCore/6sckc/src/recipes.jl:37

```
Version info:
```
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 

[ee78f7c6] Makie v0.19.5
[e9467ef8] GLMakie v0.8.5
[13f3f980] CairoMakie v0.10.5
```
I'm not sure it's the close spacing of the data that does it, but it does seems like it. Making the y-data slightly farther apart produces a plot without issue. Conversely, when the y-data is close enough to convert to the same Float32, it also works no problem.

**Comment by ffreyer** [comment] 2023-05-29 09:54
Duplicate of #2298, which was moved to #2848

**Closed by ffreyer** 2023-05-29 09:54 UTC
