### ISSUE TITLE
latex font italics are not correct

### ISSUE THREAD

**Issue by AshtonSBradley** [MakieOrg/Makie.jl#1245] opened 2021-08-21 10:50 UTC
```
cbar = Colorbar(f[1, 1][1,1],height=15,vertical=false)
Label(f[1, 1][1, 2], L"|\psi|^2\xi^2")
```
gives something like this

<img width="218" alt="Screen Shot 2021-08-21 at 10 44 16 PM" src="https://user-images.githubusercontent.com/24194258/130319372-4fdc952c-240e-474d-ab9b-bf5e2b7fa209.png">

The absolute value bars are italicised. How do I make this a more realistic LaTeX font? I would expect something like this

<img width="139" alt="Screen Shot 2021-08-21 at 10 49 09 PM" src="https://user-images.githubusercontent.com/24194258/130319424-4b6880b3-4778-4f07-81a2-00f06c75be9f.png">

**Comment by lsmohan** [comment] 2021-08-21 14:05
Could you try the following?

Label(f[1, 1][1, 2], L"\mid\psi\mid^2\xi^2")

I able to get something close to the expected output,

![image](https://user-images.githubusercontent.com/22188023/130324250-52d23433-813b-459c-9a73-55da586a9190.png)

**Comment by AshtonSBradley** [comment] 2021-08-21 20:52
ok, that looks close, thanks for this. I find it a bit strange that `\psi` is not italicised, but `|` is, which seems to invert the normal situation for latex math.

**Comment by AshtonSBradley** [comment] 2021-08-22 00:45
another example appearing in a legend (not doing anything unusual I think): there is some strange italicization being applied. All greek `\xi`, `\pi`, and `\lambda` are leaning backward.

Is this intended?

<img width="495" alt="Screen Shot 2021-08-22 at 12 42 23 PM" src="https://user-images.githubusercontent.com/24194258/130338301-6f18e769-0819-43cd-8851-bcfd63cebc7c.png">

**Comment by AshtonSBradley** [comment] 2021-08-22 00:56
```
julia> versioninfo()
Julia Version 1.7.0-beta3.0
Commit e76c9dad42 (2021-07-07 08:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by jkrumbiegel** [comment] 2021-08-22 05:41
Could you please open an issue about this at MathTeXEngine.jl? This is not LaTeX but am approximation like GR and matplotlib use, so if there are incorrect rules they need to be fixed there.

**Comment by AshtonSBradley** [comment] 2021-08-22 06:30
https://github.com/Kolaru/MathTeXEngine.jl/issues/26 

(AFAIK this issued doesn't turn up in GR or matplotlib)

**Comment by Kolaru** [comment] 2021-08-22 15:00
> (AFAIK this issued doesn't turn up in GR or matplotlib)

GR and matplotlib both have their own engine inside the library. The one Makie use is newer and pure julia and thus <s>more awesome</s> less complete yet.

As mentionned in the linked issue part of the problem is the last breaking update of `GeometryBasics.jl` (https://github.com/JuliaPlots/Makie.jl/pull/1174 and related). The dependency conflict that results prevent Makie from using the latest release of MathTeXEngine.

**Comment by SimonDanisch** [comment] 2021-08-22 15:13
Ai, seems like we should really try to merge that soon then 😅 
So @devmotion struggle is the same then:
https://github.com/JuliaPlots/Makie.jl/pull/1244

**Comment by putianyi889** [comment] 2021-11-28 19:45
Is it fixed now? I'm still having the problem with `CairoMakie0.6.6`.

**Comment by AshtonSBradley** [comment] 2022-04-23 20:51
> Ai, seems like we should really try to merge that soon then 😅 So @devmotion struggle is the same then: #1244

I think the discussion is over at [#1785](https://github.com/JuliaPlots/Makie.jl/pull/1785)

**Comment by AshtonSBradley** [comment] 2022-04-23 20:51
> Is it fixed now? I'm still having the problem with `CairoMakie0.6.6`.

I think the discussion is over at https://github.com/JuliaPlots/Makie.jl/pull/1785

**Comment by ffreyer** [comment] 2024-08-22 16:26
Fixed

**Closed by ffreyer** 2024-08-22 16:26 UTC
