### ISSUE TITLE
Add a docstring for Legend

### ISSUE THREAD

**Issue by jariji** [MakieOrg/Makie.jl#3675] opened 2024-03-04 07:13 UTC
Here is the docstring for Legend. It would be nice to show some usage signatures and examples.
 
>   Legend <: Block
> 
>   Attributes
> 
>   (type ?Legend.x in the REPL for more information about attribute x)
> 
>   alignmode, backgroundcolor, bgcolor, colgap, framecolor, framevisible, framewidth, gridshalign, gridsvalign, groupgap, halign, height, label,
>   labelcolor, labelfont, labelhalign, labeljustification, labelsize, labelvalign, linecolor, linepoints, linestyle, linewidth, margin, marker,
>   markercolor, markerpoints, markersize, markerstrokecolor, markerstrokewidth, nbanks, orientation, padding, patchcolor, patchlabelgap, patchsize,
>   patchstrokecolor, patchstrokewidth, polycolor, polypoints, polystrokecolor, polystrokewidth, rowgap, tellheight, tellwidth, titlecolor, titlefont,
>   titlegap, titlehalign, titleposition, titlesize, titlevalign, titlevisible, valign, width

**Comment by ffreyer** [comment] 2024-08-27 14:53
Legend has more descriptive docstrings now, though it still has this one and the other ones don't include attributes. 

Closing as solved and also duplicate of the more general #2928

**Closed by ffreyer** 2024-08-27 14:53 UTC
Labels: enhancement, documentation, Legend & Colorbar
