### ISSUE TITLE
GLMakie plots only part of the data

### ISSUE THREAD

**Issue by zsoerenm** [MakieOrg/Makie.jl#2413] opened 2022-11-10 13:41 UTC
Consider this MWE
```julia
using GLMakie
fig = Figure()
lines(fig[1, 1], 0:99, randn(100))
```
For a very short time the whole data is plotted correctly, but then most of the data disappears and the output looks like this:
![grafik](https://user-images.githubusercontent.com/375486/201104102-0b70fad9-c078-4edd-8ac0-5d6b25e59858.png)
I made a little video to demonstrate this with different random data:
![simplescreenrecorder-2022-11-10_14 29 56](https://user-images.githubusercontent.com/375486/201105463-72168119-80aa-476f-aa0a-3628845b36e4.gif)
Note that I need to preload `libstdc++.so.6`:
```
LD_PRELOAD=/usr/lib/libstdc++.so.6 julia --project
```
Otherwise I get errors like:
```
julia> f = Figure()
libGL error: MESA-LOADER: failed to open radeonsi: /usr/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /usr/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
┌ Warning:     GLFW couldn't create an OpenGL window.
│     This likely means, you don't have an OpenGL capable Graphic Card,
│     or you don't have an OpenGL 3.3 capable video driver installed.
│     Have a look at the troubleshooting section in the GLMakie readme:
│     https://github.com/JuliaPlots/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
└ @ GLMakie ~/.julia/packages/GLMakie/rXGL8/src/screen.jl:336
Error showing value of type Figure:
ERROR: GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig
```
However, I'm unsure if this is the root cause of the problem.
Plotting using `plot` works fine (with `libstdc++.so.6` preloaded):
```julia
using GLMakie
fig = Figure()
plot(fig[1, 1], 0:99, randn(100))
```
![grafik](https://user-images.githubusercontent.com/375486/201107004-1eaefd7d-0756-459b-94bd-d6d4a0bf463f.png)

**Comment by SimonDanisch** [comment] 2022-11-10 14:21
Duplicate of https://github.com/MakieOrg/Makie.jl/issues/1460

**Closed by SimonDanisch** 2022-11-10 14:21 UTC
