### ISSUE TITLE
Please depreciate the fig[x,y] indexing

### ISSUE THREAD

**Issue by ufechner7** [MakieOrg/Makie.jl#3742] opened 2024-03-28 15:02 UTC
### Feature description

The syntax
```julia
fig=Figure()
Label(fig[1,1], "Hello")
```
is very confusing. How can you index an array that was never explicitly created?
I suggest instead for the case you do not need any layout:
```julia
fig=Figure()
Label(fig, "Hello")
```
and in case you need a layout
```julia
fig=Figure(layout=GridLayout(2,3)) # or whatever dimensions you need
Label(fig.layout[1,1], "Hello")
```
This would be much easier to understand and less error prone.

Finally, there might also be other layouts than a GridLayout that you want to use.

**Comment by SimonDanisch** [comment] 2024-03-28 15:46
I don't think this has a change to happen at least for 3 reasons:

* It really needs a very big reason to deprecate such a core syntax so late in the game
* It can't be such a big issue, since this is the first time I hear someone wanting to change that syntax. I'm not saying that your alone with this opinion, or that it's not valid, but it certainly can't be something Makie's user base feels strongly about
* I like the syntax, and I'm sure @jkrumbiegel who came up with it likes it too.

That being said, I dont think its perfect, and we can surely talk about concrete corner cases that are especially awkward to express with the current syntax, and try to figure out ways to improve the situation without breaking the current syntax.

You could also always create your own Makie syntax as an external package - Makie was designed to be a bit more low level so that people can create their own syntax. As a matter of fact, the current syntax started as an external package: 
https://github.com/jkrumbiegel/MakieLayout.jl

I'm still closing this as not actionable ;)

**Closed by SimonDanisch** 2024-03-28 15:46 UTC
Labels: enhancement
