### ISSUE TITLE
Plotting `vlines` in unitful axis leads to crash

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#4503] opened 2024-10-21 12:15 UTC
```julia
julia> import GLMakie as Mke

julia> Mke.lines([1,2,3]u"m", [1,2,3])

julia> Mke.vlines!(1u"m")
ERROR: DimensionError:  and m are not dimensionally compatible.
```

GLMakie.jl v0.10.14

**Comment by ffreyer** [comment] 2024-11-12 15:22
Closing as duplicate of #4069 (and #4412 to some degree)

**Closed by ffreyer** 2024-11-12 15:22 UTC
Labels: bug, units
