### ISSUE TITLE
CairoMakie v0.9.0 No Longer Works with VS Code Plot Pane (or Weave.jl)

### ISSUE THREAD

**Issue by bradcarman** [MakieOrg/Makie.jl#2362] opened 2022-10-24 18:34 UTC
I'm running VS Code Julia extension on a Windows 10 machine.  CairoMakie v0.9.0 will open plots in an image window (Windows Photos Viewer).  Even if I run VS Code Julia extension command: "Julia: Enable Plot Pane", plots still are directed to the Photos application and open external to VS Code.  Additionally when using Weave.jl, figures are no longer included in weaved documents.  I've confrimed that rolling back to CairoMakie v0.8.13 returns the VS Code Plot Pane functionality (and Weave.jl as well)

**Comment by jkrumbiegel** [comment] 2022-10-24 19:15
Duplicate of https://github.com/MakieOrg/Makie.jl/issues/2331 and should hopefully be fixed as well (not aware of the Weave problem but I assume it's the same mechanism).

**Closed by jkrumbiegel** 2022-10-24 19:15 UTC
