### ISSUE TITLE
GLMakie on wsl2 does not show font correctly

### ISSUE THREAD

**Issue by PhyX-Meow** [MakieOrg/Makie.jl#3876] opened 2024-05-21 10:11 UTC
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
  - wsl2 on windows 11, archlinux. Nvidia RTX 2060S.

My plot using GLMakie looks like this:
![image](https://github.com/MakieOrg/Makie.jl/assets/17513581/a0f9bc23-c44f-4579-a063-a97afdadb12f)

No bugs when using CairoMakie
How to get the numbers display correctly?

**Comment by SimonDanisch** [comment] 2024-05-21 11:06
This looks like a duplicate of:
https://github.com/MakieOrg/Makie.jl/issues/3679

**Comment by PhyX-Meow** [comment] 2024-05-21 15:37
> This looks like a duplicate of: #3679

True, so this is really a mesa issue. I see. Maybe I should close this issue?

**Closed** 2024-05-21 15:38 UTC
Labels: bug

**Comment by PhyX-Meow** [comment] 2024-05-31 14:56
Good news to those having this issue. mesa 24.1 fixed the problem!
