### ISSUE TITLE
WGLMakie throws warning when zooming on scatter plot

### ISSUE THREAD

**Issue by bjarthur** [MakieOrg/Makie.jl#4646] opened 2024-12-05 13:32 UTC
on a 0-day master, M3 apple silicon, WGLMakie (but *not* GLMakie) prints the following warning when zooming in or out on a scatter plot:

```
using WGLMakie
f, a, s = scatter(rand(10))
```

<details>

```
julia> ┌ Warning: Error in window event callback
│   exception =
│    All non scalars need same length, Found lengths for each argument: (3, 5, 1), (Vector{Makie.GlyphCollection}, Vector{Point{3, Float64}}, Quaternion{Float64})
│    Stacktrace:
│       [1] error(s::String)
│         @ Base ./error.jl:35
│       [2] macro expansion
│         @ ~/.julia/dev/Makie/src/utilities/utilities.jl:206 [inlined]
│       [3] broadcast_foreach(::Makie.var"#1049#1050", ::Vector{Makie.GlyphCollection}, ::Vector{Point{3, Float64}}, ::Quaternion{Float64})
│         @ Makie ~/.julia/dev/Makie/src/utilities/utilities.jl:199
│       [4] unchecked_boundingbox(layouts::Vector{Makie.GlyphCollection}, positions::Vector{Point{3, Float64}}, rotations::Quaternion{Float64})
│         @ Makie ~/.julia/dev/Makie/src/layouting/text_boundingbox.jl:108
│       [5] string_boundingbox(::Vector{Makie.GlyphCollection}, ::Vector{Point{3, Float64}}, ::Vararg{Any})
│         @ Makie ~/.julia/dev/Makie/src/layouting/text_boundingbox.jl:63
│       [6] string_boundingbox(x::MakieCore.Text{Tuple{Vector{Makie.GlyphCollection}}})
│         @ Makie ~/.julia/dev/Makie/src/layouting/text_boundingbox.jl:59
│       [7] string_boundingbox(plot::MakieCore.Text{Tuple{Vector{Point{3, Float64}}}})
│         @ Makie ~/.julia/dev/Makie/src/layouting/text_boundingbox.jl:26
│    --- the above 1 lines are repeated 1 more time ---
│       [9] data_limits(plot::MakieCore.Text{Tuple{Vector{Tuple{Any, Point{2, Float32}}}}})
│         @ Makie ~/.julia/dev/Makie/src/layouting/data_limits.jl:80
│      [10] boundingbox(plot::MakieCore.Text{Tuple{Vector{Tuple{Any, Point{2, Float32}}}}}, target_space::Symbol)
│         @ Makie ~/.julia/dev/Makie/src/layouting/text_boundingbox.jl:13
│      [11] (::Makie.var"#1603#1617"{Observable{Tuple{Float32, Tuple{Float32, Float32}, Bool}}, Observable{Any}})(::Vector{Tuple{Any, Point{2, Float32}}}, ::Vararg{Any})
│         @ Makie ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:303
│      [12] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│      [13] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│      [14] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│      [15] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [16] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [17] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [18] update_ticklabel_node(closure_args::Tuple{Observable{Bool}, Observable{Any}, Observable{Float32}, Observable{Any}, Observable{Vector{Float64}}}, ticklabel_annotation_obs::Observable{Vector{Tuple{Any, Point{2, Float32}}}}, labelgap::Float32, flipped::Bool, tickpositions::Vector{Point{2, Float32}}, tickstrings::Vector{Any})
│         @ Makie ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:165
│      [19] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│      [20] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│      [21] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│      [22] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [23] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [24] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [25] setindex!
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123 [inlined]
│      [26] update_tickpos_string(closure_args::Tuple{Observable{Vector{Any}}, Observable{Vector{Point{2, Float32}}}, Observable{Vector{Float64}}, Observable{Tuple{Float32, Tuple{Float32, Float32}, Bool}}, Observable{Tuple{Float64, Float64}}}, tickvalues_labels_unfiltered::Tuple{Vector{Float64}, Vector{Any}}, reversed::Bool, scale::typeof(identity))
│         @ Makie ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:229
│      [27] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│      [28] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│      [29] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│      [30] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [31] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [32] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [33] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [34] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│    --- the above 5 lines are repeated 1 more time ---
│      [40] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [41] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [42] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [43] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [44] (::Observables.SetindexCallback)(x::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:148
│      [45] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [46] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [47] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [48] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [49] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│    --- the above 5 lines are repeated 1 more time ---
│      [55] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [56] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [57] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [58] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [59] update_computedbbox!(computedbbox::Observable{GeometryBasics.HyperRectangle{2, Float32}}, suggestedbbox::GeometryBasics.HyperRectangle{2, Float32}, alignment::Tuple{Float32, Float32}, reporteddimensions::GridLayoutBase.Dimensions, alignmode::Inside, protrusions::GridLayoutBase.RectSides{Float32}, sizeattrs::Observable{Tuple{Union{Nothing, Float32, Auto, Fixed, Relative}, Union{Nothing, Float32, Auto, Fixed, Relative}}}, autosizeobservable::Observable{Tuple{Union{Nothing, Float32}, Union{Nothing, Float32}}})
│         @ GridLayoutBase ~/.julia/packages/GridLayoutBase/xvxWi/src/layoutobservables.jl:356
│      [60] (::GridLayoutBase.var"#106#108"{Observable{GridLayoutBase.Dimensions}, Observable{Tuple{Union{Nothing, Float32, Auto, Fixed, Relative}, Union{Nothing, Float32, Auto, Fixed, Relative}}}, Observable{Tuple{Union{Nothing, Float32}, Union{Nothing, Float32}}}, Observable{Any}, Observable{GridLayoutBase.RectSides{Float32}}, Observable{GeometryBasics.HyperRectangle{2, Float32}}})(sbbox::GeometryBasics.HyperRectangle{2, Float32}, ali::Tuple{Float32, Float32})
│         @ GridLayoutBase ~/.julia/packages/GridLayoutBase/xvxWi/src/layoutobservables.jl:218
│      [61] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│      [62] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│      [63] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│      [64] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [65] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [66] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [67] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [68] align_to_bbox!(gl::GridLayout, suggestedbbox::GeometryBasics.HyperRectangle{2, Float32})
│         @ GridLayoutBase ~/.julia/packages/GridLayoutBase/xvxWi/src/gridlayout.jl:1096
│      [69] (::GridLayoutBase.var"#11#12"{GridLayout})(bbox::GeometryBasics.HyperRectangle{2, Float32})
│         @ GridLayoutBase ~/.julia/packages/GridLayoutBase/xvxWi/src/gridlayout.jl:158
│      [70] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [71] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [72] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [73] update!(gl::GridLayout)
│         @ GridLayoutBase ~/.julia/packages/GridLayoutBase/xvxWi/src/gridlayout.jl:193
│      [74] update!
│         @ ~/.julia/packages/GridLayoutBase/xvxWi/src/gridlayout.jl:1525 [inlined]
│      [75] (::GridLayoutBase.var"#14#15"{GridLayoutBase.GridContent{GridLayout}, Axis})(c::GridLayoutBase.Dimensions)
│         @ GridLayoutBase ~/.julia/packages/GridLayoutBase/xvxWi/src/gridlayout.jl:261
│      [76] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [77] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [78] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [79] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [80] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│    --- the above 5 lines are repeated 2 more times ---
│      [91] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│      [92] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│      [93] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [94] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│      [95] (::Makie.var"#1604#1618"{Observable{Any}})(idealspace::Float32, space::MakieCore.Automatic)
│         @ Makie ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:328
│      [96] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│      [97] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│      [98] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│      [99] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [100] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [101] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [102] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│    --- the above 89 lines are repeated 1 more time ---
│     [192] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│     [193] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [194] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [195] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [196] update_ticklabel_node(closure_args::Tuple{Observable{Bool}, Observable{Any}, Observable{Float32}, Observable{Any}, Observable{Vector{Float64}}}, ticklabel_annotation_obs::Observable{Vector{Tuple{Any, Point{2, Float32}}}}, labelgap::Float32, flipped::Bool, tickpositions::Vector{Point{2, Float32}}, tickstrings::Vector{Any})
│         @ Makie ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:165
│     [197] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│     [198] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│     [199] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│     [200] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [201] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [202] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [203] setindex!
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123 [inlined]
│     [204] update_tickpos_string(closure_args::Tuple{Observable{Vector{Any}}, Observable{Vector{Point{2, Float32}}}, Observable{Vector{Float64}}, Observable{Tuple{Float32, Tuple{Float32, Float32}, Bool}}, Observable{Tuple{Float64, Float64}}}, tickvalues_labels_unfiltered::Tuple{Vector{Float64}, Vector{Any}}, reversed::Bool, scale::typeof(identity))
│         @ Makie ~/.julia/dev/Makie/src/makielayout/lineaxis.jl:229
│     [205] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│     [206] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│     [207] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│     [208] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [209] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [210] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [211] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│     [212] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│    --- the above 5 lines are repeated 1 more time ---
│     [218] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [219] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [220] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [221] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│     [222] (::Observables.SetindexCallback)(x::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:148
│     [223] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [224] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [225] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [226] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│     [227] (::Observables.MapCallback)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:436
│     [228] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [229] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [230] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [231] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│     [232] adjustlimits!(la::Axis)
│         @ Makie ~/.julia/dev/Makie/src/makielayout/blocks/axis.jl:990
│     [233] (::Makie.var"#1675#1706"{Axis})(pxa::GeometryBasics.HyperRectangle{2, Int64}, lims::GeometryBasics.HyperRectangle{2, Float64})
│         @ Makie ~/.julia/dev/Makie/src/makielayout/blocks/axis.jl:507
│     [234] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│     [235] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│     [236] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│     [237] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [238] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [239] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [240] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│     [241] process_interaction(s::Makie.ScrollZoom, event::ScrollEvent, ax::Axis)
│         @ Makie ~/.julia/dev/Makie/src/makielayout/interactions.jl:289
│     [242] process_axis_event(ax::Axis, event::ScrollEvent)
│         @ Makie ~/.julia/dev/Makie/src/makielayout/blocks/axis.jl:15
│     [243] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{})
│         @ Base ./essentials.jl:1055
│     [244] invokelatest(::Any, ::Any, ::Vararg{Any})
│         @ Base ./essentials.jl:1052
│     [245] (::Observables.OnAny)(value::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:420
│     [246] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [247] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [248] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [249] setindex!
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123 [inlined]
│     [250] (::Makie.var"#1640#1642"{Scene, Observable{ScrollEvent}})(s::Tuple{Float64, Float64})
│         @ Makie ~/.julia/dev/Makie/src/makielayout/blocks/axis.jl:33
│     [251] #invokelatest#2
│         @ ./essentials.jl:1055 [inlined]
│     [252] invokelatest
│         @ ./essentials.jl:1052 [inlined]
│     [253] notify
│         @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [254] setindex!(observable::Observable, val::Any)
│         @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
└ @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:116
```

</details>

**Comment by SimonDanisch** [comment] 2024-12-05 13:52
Duplicate of: https://github.com/MakieOrg/Makie.jl/issues/4065

**Closed by SimonDanisch** 2024-12-05 13:52 UTC
Labels: bug
