### ISSUE TITLE
GLMakie.volumen function can't hide NaN dataset

### ISSUE THREAD

**Issue by HarryXiong24** [MakieOrg/Makie.jl#3342] opened 2023-10-31 22:18 UTC
- [yes] are you running newest version (version from docs) ?
- [yes] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [ MacOS M2 pro ] What platform + GPU are you on?

Hi everyone! I encountered a problem while using GLMakie.volume. I have a 3D array of data with some NaN values. If I use a heatmap to show 2D, the rendered figure can hide the NaN value part and display correctly. But when I use GLMakie.volume to render data, it can't filter the NaN values and display a cube. Ask for your help. Thank you!

![image](https://github.com/MakieOrg/Makie.jl/assets/62498853/f76aedf6-df91-40e2-a994-754b57743ab5)
![image (1)](https://github.com/MakieOrg/Makie.jl/assets/62498853/01f73f17-d347-4797-88d6-8c05e41aab95)
![image (2)](https://github.com/MakieOrg/Makie.jl/assets/62498853/f9a67757-5f67-4037-8d86-7cadd135147e)

**Comment by ffreyer** [comment] 2024-08-26 15:30
Closing as duplicate of #3181

**Closed by ffreyer** 2024-08-26 15:30 UTC
Labels: bug
