### ISSUE TITLE
WGLMakie does not support `linestyle = :dash`

### ISSUE THREAD

**Issue by staticfloat** [MakieOrg/Makie.jl#1334] opened 2021-09-22 20:46 UTC
When using `linestyle = :dash` on WGLMakie, it silently ignores it and just draws a dense line.  CairoMakie seems to display it just fine.

**Comment by jbshannon** [comment] 2022-01-29 20:46
More generally, `WGLMakie` doesn't seem to recognize any `linestyle` kwargs. I tried running the example from the docs using `WGLMakie` instead of `CairoMakie`:

```julia
using WGLMakie

f = Figure()
Axis(f[1, 1])

xs = 0:0.01:10
ys = 0.5 .* sin.(xs)

for (i, lw) in enumerate([1, 2, 3])
    lines!(xs, ys .- i/6, linestyle = nothing, linewidth = lw)
    lines!(xs, ys .- i/6 .- 1, linestyle = :dash, linewidth = lw)
    lines!(xs, ys .- i/6 .- 2, linestyle = :dot, linewidth = lw)
    lines!(xs, ys .- i/6 .- 3, linestyle = :dashdot, linewidth = lw)
    lines!(xs, ys .- i/6 .- 4, linestyle = :dashdotdot, linewidth = lw)
    lines!(xs, ys .- i/6 .- 5, linestyle = [0.5, 1.0, 1.5, 2.5], linewidth = lw)
end

f
```
which produced the following figure:
<img width="394" alt="Screen Shot 2022-01-29 at 8 39 57 PM" src="https://user-images.githubusercontent.com/46204520/151677000-d01ce242-9e5e-4f32-b38a-b9c156ce546e.png">

**Comment by ffreyer** [comment] 2023-12-27 13:52
Duplicate of #3199

**Closed by ffreyer** 2023-12-27 13:52 UTC
