### ISSUE TITLE
Legend for PolarAxis

### ISSUE THREAD

**Issue by henry2004y** [MakieOrg/Makie.jl#3455] opened 2023-12-07 15:18 UTC
Tested on GLMakie v0.9.1 and CairoMakie v0.11.1 on Win11:

```julia
f = Figure()

ax = PolarAxis(f[1, 1], title = "Theta as x")
lineobject = lines!(ax, 0..2pi, sin, color = :red, label="test")
axislegend()
```

with the error message
```julia
ERROR: MethodError: no method matching initialize_block!(::Legend, ::PolarAxis)

Closest candidates are:
  initialize_block!(::Legend; entrygroups)
   @ Makie C:\Users\hyzho\.julia\packages\Makie\pCA2E\src\makielayout\blocks\legend.jl:1

Stacktrace:
 [1] _block(T::Type{…}, fig_or_scene::Figure, args::Vector{…}, kwdict::Dict{…}, bbox::Observable{…}; kwdict_complete::Bool)
   @ Makie C:\Users\hyzho\.julia\packages\Makie\pCA2E\src\makielayout\blocks.jl:388
 [2] _block
   @ C:\Users\hyzho\.julia\packages\Makie\pCA2E\src\makielayout\blocks.jl:308 [inlined]
```

**Comment by ffreyer** [comment] 2024-08-26 19:27
Closing as duplicate of #3110

**Closed by ffreyer** 2024-08-26 19:27 UTC
Labels: bug, MakieLayout
